//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for AddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="IpAddress" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}IpAddressType"/>
 *         &lt;element name="IpMask" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}IpAddressType"/>
 *         &lt;element name="PortBegin" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="PortEnd" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressType", propOrder = {

})
public class AddressType {

    @XmlElement(name = "IpAddress", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ipAddress;
    @XmlElement(name = "IpMask", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ipMask;
    @XmlElement(name = "PortBegin")
    @XmlSchemaType(name = "unsignedShort")
    protected int portBegin;
    @XmlElement(name = "PortEnd")
    @XmlSchemaType(name = "unsignedShort")
    protected int portEnd;

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the ipMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpMask() {
        return ipMask;
    }

    /**
     * Sets the value of the ipMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpMask(String value) {
        this.ipMask = value;
    }

    /**
     * Gets the value of the portBegin property.
     * 
     */
    public int getPortBegin() {
        return portBegin;
    }

    /**
     * Sets the value of the portBegin property.
     * 
     */
    public void setPortBegin(int value) {
        this.portBegin = value;
    }

    /**
     * Gets the value of the portEnd property.
     * 
     */
    public int getPortEnd() {
        return portEnd;
    }

    /**
     * Sets the value of the portEnd property.
     * 
     */
    public void setPortEnd(int value) {
        this.portEnd = value;
    }

}
