//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for AgentRuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AgentRuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="SelectionCriteria" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AgentProperty" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}NameValuePropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="selectAllAgents" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DataCollectors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DataCollector" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Configuration" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence minOccurs="0">
 *                                       &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                           &lt;attribute name="friendlyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="assemblyQualifiedName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgentRuleType", propOrder = {

})
public class AgentRuleType {

    @XmlElement(name = "SelectionCriteria")
    protected SelectionCriteria selectionCriteria;
    @XmlElement(name = "DataCollectors")
    protected DataCollectors dataCollectors;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the selectionCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.AgentRuleType.SelectionCriteria }
     *     
     */
    public SelectionCriteria getSelectionCriteria() {
        return selectionCriteria;
    }

    /**
     * Sets the value of the selectionCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.AgentRuleType.SelectionCriteria }
     *     
     */
    public void setSelectionCriteria(SelectionCriteria value) {
        this.selectionCriteria = value;
    }

    /**
     * Gets the value of the dataCollectors property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.AgentRuleType.DataCollectors }
     *     
     */
    public DataCollectors getDataCollectors() {
        return dataCollectors;
    }

    /**
     * Sets the value of the dataCollectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.AgentRuleType.DataCollectors }
     *     
     */
    public void setDataCollectors(DataCollectors value) {
        this.dataCollectors = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataCollector" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Configuration" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence minOccurs="0">
     *                             &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                 &lt;attribute name="friendlyName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="assemblyQualifiedName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataCollector"
    })
    public static class DataCollectors {

        @XmlElement(name = "DataCollector")
        protected List<DataCollector> dataCollector;

        /**
         * Gets the value of the dataCollector property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataCollector property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataCollector().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.expedia.aggregator.data.AgentRuleType.DataCollectors.DataCollector }
         * 
         * 
         */
        public List<DataCollector> getDataCollector() {
            if (dataCollector == null) {
                dataCollector = new ArrayList<DataCollector>();
            }
            return this.dataCollector;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Configuration" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence minOccurs="0">
         *                   &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="friendlyName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="assemblyQualifiedName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "configuration"
        })
        public static class DataCollector {

            @XmlElement(name = "Configuration")
            protected Configuration configuration;
            @XmlAttribute(name = "uri", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String uri;
            @XmlAttribute(name = "friendlyName")
            protected String friendlyName;
            @XmlAttribute(name = "assemblyQualifiedName", required = true)
            protected String assemblyQualifiedName;
            @XmlAttribute(name = "enabled")
            protected Boolean enabled;

            /**
             * Gets the value of the configuration property.
             * 
             * @return
             *     possible object is
             *     {@link com.expedia.aggregator.data.AgentRuleType.DataCollectors.DataCollector.Configuration }
             *     
             */
            public Configuration getConfiguration() {
                return configuration;
            }

            /**
             * Sets the value of the configuration property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.expedia.aggregator.data.AgentRuleType.DataCollectors.DataCollector.Configuration }
             *     
             */
            public void setConfiguration(Configuration value) {
                this.configuration = value;
            }

            /**
             * Gets the value of the uri property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUri() {
                return uri;
            }

            /**
             * Sets the value of the uri property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUri(String value) {
                this.uri = value;
            }

            /**
             * Gets the value of the friendlyName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFriendlyName() {
                return friendlyName;
            }

            /**
             * Sets the value of the friendlyName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFriendlyName(String value) {
                this.friendlyName = value;
            }

            /**
             * Gets the value of the assemblyQualifiedName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAssemblyQualifiedName() {
                return assemblyQualifiedName;
            }

            /**
             * Sets the value of the assemblyQualifiedName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAssemblyQualifiedName(String value) {
                this.assemblyQualifiedName = value;
            }

            /**
             * Gets the value of the enabled property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isEnabled() {
                if (enabled == null) {
                    return true;
                } else {
                    return enabled;
                }
            }

            /**
             * Sets the value of the enabled property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setEnabled(Boolean value) {
                this.enabled = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence minOccurs="0">
             *         &lt;any processContents='lax' maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "any"
            })
            public static class Configuration {

                @XmlAnyElement(lax = true)
                protected List<Object> any;

                /**
                 * Gets the value of the any property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the any property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAny().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link org.w3c.dom.Element }
                 * {@link Object }
                 * 
                 * 
                 */
                public List<Object> getAny() {
                    if (any == null) {
                        any = new ArrayList<Object>();
                    }
                    return this.any;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AgentProperty" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}NameValuePropertyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="selectAllAgents" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "agentProperty"
    })
    public static class SelectionCriteria {

        @XmlElement(name = "AgentProperty")
        protected List<NameValuePropertyType> agentProperty;
        @XmlAttribute(name = "selectAllAgents")
        protected Boolean selectAllAgents;

        /**
         * Gets the value of the agentProperty property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the agentProperty property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAgentProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.expedia.aggregator.data.NameValuePropertyType }
         * 
         * 
         */
        public List<NameValuePropertyType> getAgentProperty() {
            if (agentProperty == null) {
                agentProperty = new ArrayList<NameValuePropertyType>();
            }
            return this.agentProperty;
        }

        /**
         * Gets the value of the selectAllAgents property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isSelectAllAgents() {
            return selectAllAgents;
        }

        /**
         * Sets the value of the selectAllAgents property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSelectAllAgents(Boolean value) {
            this.selectAllAgents = value;
        }

    }

}
