//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Constant" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}ConstantTrafficType"/>
 *         &lt;element name="Exponential" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}ExponentialTrafficType"/>
 *         &lt;element name="Pareto" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}ParetoTrafficType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "constant",
    "exponential",
    "pareto"
})
@XmlRootElement(name = "BackgroundTraffic")
public class BackgroundTraffic {

    @XmlElement(name = "Constant")
    protected ConstantTrafficType constant;
    @XmlElement(name = "Exponential")
    protected ExponentialTrafficType exponential;
    @XmlElement(name = "Pareto")
    protected ParetoTrafficType pareto;

    /**
     * Gets the value of the constant property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.ConstantTrafficType }
     *     
     */
    public ConstantTrafficType getConstant() {
        return constant;
    }

    /**
     * Sets the value of the constant property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.ConstantTrafficType }
     *     
     */
    public void setConstant(ConstantTrafficType value) {
        this.constant = value;
    }

    /**
     * Gets the value of the exponential property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.ExponentialTrafficType }
     *     
     */
    public ExponentialTrafficType getExponential() {
        return exponential;
    }

    /**
     * Sets the value of the exponential property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.ExponentialTrafficType }
     *     
     */
    public void setExponential(ExponentialTrafficType value) {
        this.exponential = value;
    }

    /**
     * Gets the value of the pareto property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.ParetoTrafficType }
     *     
     */
    public ParetoTrafficType getPareto() {
        return pareto;
    }

    /**
     * Sets the value of the pareto property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.ParetoTrafficType }
     *     
     */
    public void setPareto(ParetoTrafficType value) {
        this.pareto = value;
    }

}
