//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Speed" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}SpeedType"/>
 *         &lt;element name="QueueManagement" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="RedQueue" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}RedQueueType"/>
 *                   &lt;element name="NormalQueue" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}NormalQueueType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Bandwidth")
public class Bandwidth {

    @XmlElement(name = "Speed", required = true)
    protected SpeedType speed;
    @XmlElement(name = "QueueManagement")
    protected QueueManagement queueManagement;

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.SpeedType }
     *     
     */
    public SpeedType getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.SpeedType }
     *     
     */
    public void setSpeed(SpeedType value) {
        this.speed = value;
    }

    /**
     * Gets the value of the queueManagement property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.Bandwidth.QueueManagement }
     *     
     */
    public QueueManagement getQueueManagement() {
        return queueManagement;
    }

    /**
     * Sets the value of the queueManagement property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.Bandwidth.QueueManagement }
     *     
     */
    public void setQueueManagement(QueueManagement value) {
        this.queueManagement = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="RedQueue" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}RedQueueType"/>
     *         &lt;element name="NormalQueue" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}NormalQueueType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "redQueue",
        "normalQueue"
    })
    public static class QueueManagement {

        @XmlElement(name = "RedQueue")
        protected RedQueueType redQueue;
        @XmlElement(name = "NormalQueue")
        protected NormalQueueType normalQueue;

        /**
         * Gets the value of the redQueue property.
         * 
         * @return
         *     possible object is
         *     {@link com.expedia.aggregator.data.RedQueueType }
         *     
         */
        public RedQueueType getRedQueue() {
            return redQueue;
        }

        /**
         * Sets the value of the redQueue property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.expedia.aggregator.data.RedQueueType }
         *     
         */
        public void setRedQueue(RedQueueType value) {
            this.redQueue = value;
        }

        /**
         * Gets the value of the normalQueue property.
         * 
         * @return
         *     possible object is
         *     {@link com.expedia.aggregator.data.NormalQueueType }
         *     
         */
        public NormalQueueType getNormalQueue() {
            return normalQueue;
        }

        /**
         * Sets the value of the normalQueue property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.expedia.aggregator.data.NormalQueueType }
         *     
         */
        public void setNormalQueue(NormalQueueType value) {
            this.normalQueue = value;
        }

    }

}
