//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CollectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CollectorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UriAttachments" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}UriAttachmentsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="agentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="agentDisplayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="collectorDisplayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isFromRemoteAgent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CollectorType", propOrder = {
    "uriAttachments"
})
public class CollectorType {

    @XmlElement(name = "UriAttachments")
    protected UriAttachmentsType uriAttachments;
    @XmlAttribute(name = "agentName", required = true)
    protected String agentName;
    @XmlAttribute(name = "agentDisplayName")
    protected String agentDisplayName;
    @XmlAttribute(name = "collectorDisplayName")
    protected String collectorDisplayName;
    @XmlAttribute(name = "isFromRemoteAgent")
    protected Boolean isFromRemoteAgent;
    @XmlAttribute(name = "uri", required = true)
    protected String uri;

    /**
     * Gets the value of the uriAttachments property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.UriAttachmentsType }
     *     
     */
    public UriAttachmentsType getUriAttachments() {
        return uriAttachments;
    }

    /**
     * Sets the value of the uriAttachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.UriAttachmentsType }
     *     
     */
    public void setUriAttachments(UriAttachmentsType value) {
        this.uriAttachments = value;
    }

    /**
     * Gets the value of the agentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * Sets the value of the agentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentName(String value) {
        this.agentName = value;
    }

    /**
     * Gets the value of the agentDisplayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentDisplayName() {
        return agentDisplayName;
    }

    /**
     * Sets the value of the agentDisplayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentDisplayName(String value) {
        this.agentDisplayName = value;
    }

    /**
     * Gets the value of the collectorDisplayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectorDisplayName() {
        return collectorDisplayName;
    }

    /**
     * Sets the value of the collectorDisplayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectorDisplayName(String value) {
        this.collectorDisplayName = value;
    }

    /**
     * Gets the value of the isFromRemoteAgent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsFromRemoteAgent() {
        if (isFromRemoteAgent == null) {
            return false;
        } else {
            return isFromRemoteAgent;
        }
    }

    /**
     * Sets the value of the isFromRemoteAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFromRemoteAgent(Boolean value) {
        this.isFromRemoteAgent = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

}
