//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataCollectorMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataCollectorMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="level" use="required" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}DataCollectorMessageLevelType" />
 *       &lt;attribute name="agentName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dataCollectorUri" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dataCollectorFriendlyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataCollectorMessageType", propOrder = {
    "text"
})
@XmlSeeAlso({
    DataCollectorExceptionMessageType.class
})
public class DataCollectorMessageType {

    @XmlElement(name = "Text", required = true)
    protected String text;
    @XmlAttribute(name = "level", required = true)
    protected DataCollectorMessageLevelType level;
    @XmlAttribute(name = "agentName", required = true)
    protected String agentName;
    @XmlAttribute(name = "timestamp", required = true)
    protected String timestamp;
    @XmlAttribute(name = "dataCollectorUri")
    protected String dataCollectorUri;
    @XmlAttribute(name = "dataCollectorFriendlyName")
    protected String dataCollectorFriendlyName;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.DataCollectorMessageLevelType }
     *     
     */
    public DataCollectorMessageLevelType getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.DataCollectorMessageLevelType }
     *     
     */
    public void setLevel(DataCollectorMessageLevelType value) {
        this.level = value;
    }

    /**
     * Gets the value of the agentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * Sets the value of the agentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentName(String value) {
        this.agentName = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the dataCollectorUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCollectorUri() {
        return dataCollectorUri;
    }

    /**
     * Sets the value of the dataCollectorUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCollectorUri(String value) {
        this.dataCollectorUri = value;
    }

    /**
     * Gets the value of the dataCollectorFriendlyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCollectorFriendlyName() {
        return dataCollectorFriendlyName;
    }

    /**
     * Sets the value of the dataCollectorFriendlyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCollectorFriendlyName(String value) {
        this.dataCollectorFriendlyName = value;
    }

}
