//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Declarative web test in TRX file
 * 
 * <p>Java class for DeclarativeWebTestElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeclarativeWebTestElementType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}BaseTestType">
 *       &lt;attribute name="persistedWebTest" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeclarativeWebTestElementType")
public class DeclarativeWebTestElementType
    extends BaseTestType
{

    @XmlAttribute(name = "persistedWebTest", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String persistedWebTest;

    /**
     * Gets the value of the persistedWebTest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersistedWebTest() {
        return persistedWebTest;
    }

    /**
     * Sets the value of the persistedWebTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersistedWebTest(String value) {
        this.persistedWebTest = value;
    }

}
