//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DiscoveryCacheType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiscoveryCacheType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RemoteAgents" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Controller" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Agent" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element name="DataCollectorInformation" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}DataCollectorInformationType" minOccurs="0"/>
 *                                       &lt;element name="AgentProperties" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Property" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}NameValuePropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/all>
 *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiscoveryCacheType", propOrder = {
    "remoteAgents"
})
public class DiscoveryCacheType {

    @XmlElement(name = "RemoteAgents")
    protected RemoteAgents remoteAgents;

    /**
     * Gets the value of the remoteAgents property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.DiscoveryCacheType.RemoteAgents }
     *     
     */
    public RemoteAgents getRemoteAgents() {
        return remoteAgents;
    }

    /**
     * Sets the value of the remoteAgents property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.DiscoveryCacheType.RemoteAgents }
     *     
     */
    public void setRemoteAgents(RemoteAgents value) {
        this.remoteAgents = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Controller" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Agent" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element name="DataCollectorInformation" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}DataCollectorInformationType" minOccurs="0"/>
     *                             &lt;element name="AgentProperties" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Property" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}NameValuePropertyType" maxOccurs="unbounded" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/all>
     *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "controller"
    })
    public static class RemoteAgents {

        @XmlElement(name = "Controller")
        protected List<Controller> controller;

        /**
         * Gets the value of the controller property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the controller property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getController().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.expedia.aggregator.data.DiscoveryCacheType.RemoteAgents.Controller }
         * 
         * 
         */
        public List<Controller> getController() {
            if (controller == null) {
                controller = new ArrayList<Controller>();
            }
            return this.controller;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Agent" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element name="DataCollectorInformation" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}DataCollectorInformationType" minOccurs="0"/>
         *                   &lt;element name="AgentProperties" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Property" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}NameValuePropertyType" maxOccurs="unbounded" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/all>
         *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "agent"
        })
        public static class Controller {

            @XmlElement(name = "Agent")
            protected List<Agent> agent;
            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the agent property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the agent property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAgent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link com.expedia.aggregator.data.DiscoveryCacheType.RemoteAgents.Controller.Agent }
             * 
             * 
             */
            public List<Agent> getAgent() {
                if (agent == null) {
                    agent = new ArrayList<Agent>();
                }
                return this.agent;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="DataCollectorInformation" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}DataCollectorInformationType" minOccurs="0"/>
             *         &lt;element name="AgentProperties" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Property" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}NameValuePropertyType" maxOccurs="unbounded" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/all>
             *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class Agent {

                @XmlElement(name = "DataCollectorInformation")
                protected DataCollectorInformationType dataCollectorInformation;
                @XmlElement(name = "AgentProperties")
                protected AgentProperties agentProperties;
                @XmlAttribute(name = "name", required = true)
                protected String name;

                /**
                 * Gets the value of the dataCollectorInformation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link com.expedia.aggregator.data.DataCollectorInformationType }
                 *     
                 */
                public DataCollectorInformationType getDataCollectorInformation() {
                    return dataCollectorInformation;
                }

                /**
                 * Sets the value of the dataCollectorInformation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link com.expedia.aggregator.data.DataCollectorInformationType }
                 *     
                 */
                public void setDataCollectorInformation(DataCollectorInformationType value) {
                    this.dataCollectorInformation = value;
                }

                /**
                 * Gets the value of the agentProperties property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link com.expedia.aggregator.data.DiscoveryCacheType.RemoteAgents.Controller.Agent.AgentProperties }
                 *     
                 */
                public AgentProperties getAgentProperties() {
                    return agentProperties;
                }

                /**
                 * Sets the value of the agentProperties property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link com.expedia.aggregator.data.DiscoveryCacheType.RemoteAgents.Controller.Agent.AgentProperties }
                 *     
                 */
                public void setAgentProperties(AgentProperties value) {
                    this.agentProperties = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Property" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}NameValuePropertyType" maxOccurs="unbounded" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "property"
                })
                public static class AgentProperties {

                    @XmlElement(name = "Property")
                    protected List<NameValuePropertyType> property;

                    /**
                     * Gets the value of the property property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the property property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getProperty().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link com.expedia.aggregator.data.NameValuePropertyType }
                     * 
                     * 
                     */
                    public List<NameValuePropertyType> getProperty() {
                        if (property == null) {
                            property = new ArrayList<NameValuePropertyType>();
                        }
                        return this.property;
                    }

                }

            }

        }

    }

}
