//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Random" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}RandomErrorType"/>
 *         &lt;element name="Statistical" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}StatisticalErrorType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "random",
    "statistical"
})
@XmlRootElement(name = "Error")
public class Error {

    @XmlElement(name = "Random")
    protected RandomErrorType random;
    @XmlElement(name = "Statistical")
    protected StatisticalErrorType statistical;

    /**
     * Gets the value of the random property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.RandomErrorType }
     *     
     */
    public RandomErrorType getRandom() {
        return random;
    }

    /**
     * Sets the value of the random property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.RandomErrorType }
     *     
     */
    public void setRandom(RandomErrorType value) {
        this.random = value;
    }

    /**
     * Gets the value of the statistical property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.StatisticalErrorType }
     *     
     */
    public StatisticalErrorType getStatistical() {
        return statistical;
    }

    /**
     * Sets the value of the statistical property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.StatisticalErrorType }
     *     
     */
    public void setStatistical(StatisticalErrorType value) {
        this.statistical = value;
    }

}
