//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExponentialTrafficType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExponentialTrafficType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}ConstantTrafficType">
 *       &lt;sequence>
 *         &lt;element name="BurstTime" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}SecType"/>
 *         &lt;element name="IdleTime" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}SecType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExponentialTrafficType", propOrder = {
    "burstTime",
    "idleTime"
})
@XmlSeeAlso({
    ParetoTrafficType.class
})
public class ExponentialTrafficType
    extends ConstantTrafficType
{

    @XmlElement(name = "BurstTime", required = true)
    protected SecType burstTime;
    @XmlElement(name = "IdleTime", required = true)
    protected SecType idleTime;

    /**
     * Gets the value of the burstTime property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.SecType }
     *     
     */
    public SecType getBurstTime() {
        return burstTime;
    }

    /**
     * Sets the value of the burstTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.SecType }
     *     
     */
    public void setBurstTime(SecType value) {
        this.burstTime = value;
    }

    /**
     * Gets the value of the idleTime property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.SecType }
     *     
     */
    public SecType getIdleTime() {
        return idleTime;
    }

    /**
     * Sets the value of the idleTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.SecType }
     *     
     */
    public void setIdleTime(SecType value) {
        this.idleTime = value;
    }

}
