//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LinearLatencyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinearLatencyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}UniformLatencyType">
 *       &lt;sequence>
 *         &lt;element name="Period" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}SecType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinearLatencyType", propOrder = {
    "period"
})
public class LinearLatencyType
    extends UniformLatencyType
{

    @XmlElement(name = "Period", required = true)
    protected SecType period;

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.SecType }
     *     
     */
    public SecType getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.SecType }
     *     
     */
    public void setPeriod(SecType value) {
        this.period = value;
    }

}
