//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}Latency" minOccurs="0"/>
 *         &lt;element ref="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}Error" minOccurs="0"/>
 *         &lt;element ref="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}Loss" minOccurs="0"/>
 *         &lt;element ref="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}Bandwidth" minOccurs="0"/>
 *         &lt;element ref="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}BackgroundTraffic" minOccurs="0"/>
 *         &lt;element ref="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}Reorder" minOccurs="0"/>
 *         &lt;element ref="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}Disconnection" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="dir" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="upstream"/>
 *             &lt;enumeration value="downstream"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "LinkRule")
public class LinkRule {

    @XmlElement(name = "Latency")
    protected Latency latency;
    @XmlElement(name = "Error")
    protected Error error;
    @XmlElement(name = "Loss")
    protected Loss loss;
    @XmlElement(name = "Bandwidth")
    protected Bandwidth bandwidth;
    @XmlElement(name = "BackgroundTraffic")
    protected BackgroundTraffic backgroundTraffic;
    @XmlElement(name = "Reorder")
    protected Reorder reorder;
    @XmlElement(name = "Disconnection")
    protected Disconnection disconnection;
    @XmlAttribute(name = "dir", required = true)
    protected String dir;

    /**
     * Gets the value of the latency property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.Latency }
     *     
     */
    public Latency getLatency() {
        return latency;
    }

    /**
     * Sets the value of the latency property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.Latency }
     *     
     */
    public void setLatency(Latency value) {
        this.latency = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the loss property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.Loss }
     *     
     */
    public Loss getLoss() {
        return loss;
    }

    /**
     * Sets the value of the loss property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.Loss }
     *     
     */
    public void setLoss(Loss value) {
        this.loss = value;
    }

    /**
     * Gets the value of the bandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.Bandwidth }
     *     
     */
    public Bandwidth getBandwidth() {
        return bandwidth;
    }

    /**
     * Sets the value of the bandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.Bandwidth }
     *     
     */
    public void setBandwidth(Bandwidth value) {
        this.bandwidth = value;
    }

    /**
     * Gets the value of the backgroundTraffic property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.BackgroundTraffic }
     *     
     */
    public BackgroundTraffic getBackgroundTraffic() {
        return backgroundTraffic;
    }

    /**
     * Sets the value of the backgroundTraffic property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.BackgroundTraffic }
     *     
     */
    public void setBackgroundTraffic(BackgroundTraffic value) {
        this.backgroundTraffic = value;
    }

    /**
     * Gets the value of the reorder property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.Reorder }
     *     
     */
    public Reorder getReorder() {
        return reorder;
    }

    /**
     * Sets the value of the reorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.Reorder }
     *     
     */
    public void setReorder(Reorder value) {
        this.reorder = value;
    }

    /**
     * Gets the value of the disconnection property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.Disconnection }
     *     
     */
    public Disconnection getDisconnection() {
        return disconnection;
    }

    /**
     * Sets the value of the disconnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.Disconnection }
     *     
     */
    public void setDisconnection(Disconnection value) {
        this.disconnection = value;
    }

    /**
     * Gets the value of the dir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDir() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDir(String value) {
        this.dir = value;
    }

}
