//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoadTestRunStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LoadTestRunStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Connecting"/>
 *     &lt;enumeration value="InitializingResultsCollection"/>
 *     &lt;enumeration value="NotStarted"/>
 *     &lt;enumeration value="Queued"/>
 *     &lt;enumeration value="Starting"/>
 *     &lt;enumeration value="Stopping"/>
 *     &lt;enumeration value="Stopped"/>
 *     &lt;enumeration value="WarmingUp"/>
 *     &lt;enumeration value="WritingResults"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LoadTestRunStatusType")
@XmlEnum
public enum LoadTestRunStatusType {

    @XmlEnumValue("Connecting")
    CONNECTING("Connecting"),
    @XmlEnumValue("InitializingResultsCollection")
    INITIALIZING_RESULTS_COLLECTION("InitializingResultsCollection"),
    @XmlEnumValue("NotStarted")
    NOT_STARTED("NotStarted"),
    @XmlEnumValue("Queued")
    QUEUED("Queued"),
    @XmlEnumValue("Starting")
    STARTING("Starting"),
    @XmlEnumValue("Stopping")
    STOPPING("Stopping"),
    @XmlEnumValue("Stopped")
    STOPPED("Stopped"),
    @XmlEnumValue("WarmingUp")
    WARMING_UP("WarmingUp"),
    @XmlEnumValue("WritingResults")
    WRITING_RESULTS("WritingResults");
    private final String value;

    LoadTestRunStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LoadTestRunStatusType fromValue(String v) {
        for (LoadTestRunStatusType c: LoadTestRunStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
