//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoadTestRunDescriptorViewType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LoadTestRunDescriptorViewType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Graph"/>
 *     &lt;enumeration value="Summary"/>
 *     &lt;enumeration value="Table"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LoadTestRunDescriptorViewType")
@XmlEnum
public enum LoadTestRunDescriptorViewType {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Graph")
    GRAPH("Graph"),
    @XmlEnumValue("Summary")
    SUMMARY("Summary"),
    @XmlEnumValue("Table")
    TABLE("Table");
    private final String value;

    LoadTestRunDescriptorViewType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LoadTestRunDescriptorViewType fromValue(String v) {
        for (LoadTestRunDescriptorViewType c: LoadTestRunDescriptorViewType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
