//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoadTestResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoadTestResultType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}TestResultAggregationType">
 *       &lt;sequence>
 *         &lt;element name="AnalyzerViewState" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LoadTestRunDescriptor" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}LoadTestRunDescriptorType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Summary" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PerformanceCounterResults" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PerformanceCounterResult" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="machineName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="categoryName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="instanceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="counterName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="isOverallResultCounter" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                                     &lt;attribute name="higherIsBetter" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PageSummaries" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PageSummary" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                     &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                     &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                     &lt;attribute name="pageCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="responseTime" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TestSummaries" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TestSummary" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="totalTests" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="testsFailed" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="averageDuration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TransactionSummaries" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TransactionSummary" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="transactionName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="transactionCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="elapsedTime" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="responseTime" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="runStatus" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}LoadTestRunStatusType" default="NotStarted" />
 *       &lt;attribute name="runId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="controllerStartTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="loadTestDuration" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="loadTestWarmupTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="previouslyViewed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="resultsRepositoryConnectString" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resultsStoreType" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}LoadTestResultStoreType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoadTestResultType", propOrder = {
    "analyzerViewState",
    "summary"
})
public class LoadTestResultType
    extends TestResultAggregationType
{

    @XmlElement(name = "AnalyzerViewState")
    protected AnalyzerViewState analyzerViewState;
    @XmlElement(name = "Summary")
    protected Summary summary;
    @XmlAttribute(name = "runStatus")
    protected LoadTestRunStatusType runStatus;
    @XmlAttribute(name = "runId", required = true)
    protected int runId;
    @XmlAttribute(name = "controllerStartTime")
    protected String controllerStartTime;
    @XmlAttribute(name = "loadTestDuration")
    protected Integer loadTestDuration;
    @XmlAttribute(name = "loadTestWarmupTime")
    protected Integer loadTestWarmupTime;
    @XmlAttribute(name = "previouslyViewed")
    protected Boolean previouslyViewed;
    @XmlAttribute(name = "resultsRepositoryConnectString")
    protected String resultsRepositoryConnectString;
    @XmlAttribute(name = "resultsStoreType")
    protected LoadTestResultStoreType resultsStoreType;

    /**
     * Gets the value of the analyzerViewState property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.LoadTestResultType.AnalyzerViewState }
     *     
     */
    public AnalyzerViewState getAnalyzerViewState() {
        return analyzerViewState;
    }

    /**
     * Sets the value of the analyzerViewState property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.LoadTestResultType.AnalyzerViewState }
     *     
     */
    public void setAnalyzerViewState(AnalyzerViewState value) {
        this.analyzerViewState = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.LoadTestResultType.Summary }
     *     
     */
    public Summary getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.LoadTestResultType.Summary }
     *     
     */
    public void setSummary(Summary value) {
        this.summary = value;
    }

    /**
     * Gets the value of the runStatus property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.LoadTestRunStatusType }
     *     
     */
    public LoadTestRunStatusType getRunStatus() {
        if (runStatus == null) {
            return LoadTestRunStatusType.NOT_STARTED;
        } else {
            return runStatus;
        }
    }

    /**
     * Sets the value of the runStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.LoadTestRunStatusType }
     *     
     */
    public void setRunStatus(LoadTestRunStatusType value) {
        this.runStatus = value;
    }

    /**
     * Gets the value of the runId property.
     * 
     */
    public int getRunId() {
        return runId;
    }

    /**
     * Sets the value of the runId property.
     * 
     */
    public void setRunId(int value) {
        this.runId = value;
    }

    /**
     * Gets the value of the controllerStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControllerStartTime() {
        return controllerStartTime;
    }

    /**
     * Sets the value of the controllerStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControllerStartTime(String value) {
        this.controllerStartTime = value;
    }

    /**
     * Gets the value of the loadTestDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLoadTestDuration() {
        return loadTestDuration;
    }

    /**
     * Sets the value of the loadTestDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLoadTestDuration(Integer value) {
        this.loadTestDuration = value;
    }

    /**
     * Gets the value of the loadTestWarmupTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLoadTestWarmupTime() {
        return loadTestWarmupTime;
    }

    /**
     * Sets the value of the loadTestWarmupTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLoadTestWarmupTime(Integer value) {
        this.loadTestWarmupTime = value;
    }

    /**
     * Gets the value of the previouslyViewed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPreviouslyViewed() {
        if (previouslyViewed == null) {
            return false;
        } else {
            return previouslyViewed;
        }
    }

    /**
     * Sets the value of the previouslyViewed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreviouslyViewed(Boolean value) {
        this.previouslyViewed = value;
    }

    /**
     * Gets the value of the resultsRepositoryConnectString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultsRepositoryConnectString() {
        return resultsRepositoryConnectString;
    }

    /**
     * Sets the value of the resultsRepositoryConnectString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultsRepositoryConnectString(String value) {
        this.resultsRepositoryConnectString = value;
    }

    /**
     * Gets the value of the resultsStoreType property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.LoadTestResultStoreType }
     *     
     */
    public LoadTestResultStoreType getResultsStoreType() {
        return resultsStoreType;
    }

    /**
     * Sets the value of the resultsStoreType property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.LoadTestResultStoreType }
     *     
     */
    public void setResultsStoreType(LoadTestResultStoreType value) {
        this.resultsStoreType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LoadTestRunDescriptor" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}LoadTestRunDescriptorType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "loadTestRunDescriptor"
    })
    public static class AnalyzerViewState {

        @XmlElement(name = "LoadTestRunDescriptor")
        protected LoadTestRunDescriptorType loadTestRunDescriptor;

        /**
         * Gets the value of the loadTestRunDescriptor property.
         * 
         * @return
         *     possible object is
         *     {@link com.expedia.aggregator.data.LoadTestRunDescriptorType }
         *     
         */
        public LoadTestRunDescriptorType getLoadTestRunDescriptor() {
            return loadTestRunDescriptor;
        }

        /**
         * Sets the value of the loadTestRunDescriptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.expedia.aggregator.data.LoadTestRunDescriptorType }
         *     
         */
        public void setLoadTestRunDescriptor(LoadTestRunDescriptorType value) {
            this.loadTestRunDescriptor = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PerformanceCounterResults" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PerformanceCounterResult" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="machineName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="categoryName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="instanceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="counterName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="isOverallResultCounter" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *                           &lt;attribute name="higherIsBetter" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PageSummaries" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PageSummary" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                           &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                           &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                           &lt;attribute name="pageCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="responseTime" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TestSummaries" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TestSummary" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="totalTests" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="testsFailed" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="averageDuration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TransactionSummaries" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TransactionSummary" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="transactionName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="transactionCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="elapsedTime" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="responseTime" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "performanceCounterResults",
        "pageSummaries",
        "testSummaries",
        "transactionSummaries"
    })
    public static class Summary {

        @XmlElement(name = "PerformanceCounterResults")
        protected PerformanceCounterResults performanceCounterResults;
        @XmlElement(name = "PageSummaries")
        protected PageSummaries pageSummaries;
        @XmlElement(name = "TestSummaries")
        protected TestSummaries testSummaries;
        @XmlElement(name = "TransactionSummaries")
        protected TransactionSummaries transactionSummaries;

        /**
         * Gets the value of the performanceCounterResults property.
         * 
         * @return
         *     possible object is
         *     {@link com.expedia.aggregator.data.LoadTestResultType.Summary.PerformanceCounterResults }
         *     
         */
        public PerformanceCounterResults getPerformanceCounterResults() {
            return performanceCounterResults;
        }

        /**
         * Sets the value of the performanceCounterResults property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.expedia.aggregator.data.LoadTestResultType.Summary.PerformanceCounterResults }
         *     
         */
        public void setPerformanceCounterResults(PerformanceCounterResults value) {
            this.performanceCounterResults = value;
        }

        /**
         * Gets the value of the pageSummaries property.
         * 
         * @return
         *     possible object is
         *     {@link com.expedia.aggregator.data.LoadTestResultType.Summary.PageSummaries }
         *     
         */
        public PageSummaries getPageSummaries() {
            return pageSummaries;
        }

        /**
         * Sets the value of the pageSummaries property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.expedia.aggregator.data.LoadTestResultType.Summary.PageSummaries }
         *     
         */
        public void setPageSummaries(PageSummaries value) {
            this.pageSummaries = value;
        }

        /**
         * Gets the value of the testSummaries property.
         * 
         * @return
         *     possible object is
         *     {@link com.expedia.aggregator.data.LoadTestResultType.Summary.TestSummaries }
         *     
         */
        public TestSummaries getTestSummaries() {
            return testSummaries;
        }

        /**
         * Sets the value of the testSummaries property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.expedia.aggregator.data.LoadTestResultType.Summary.TestSummaries }
         *     
         */
        public void setTestSummaries(TestSummaries value) {
            this.testSummaries = value;
        }

        /**
         * Gets the value of the transactionSummaries property.
         * 
         * @return
         *     possible object is
         *     {@link com.expedia.aggregator.data.LoadTestResultType.Summary.TransactionSummaries }
         *     
         */
        public TransactionSummaries getTransactionSummaries() {
            return transactionSummaries;
        }

        /**
         * Sets the value of the transactionSummaries property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.expedia.aggregator.data.LoadTestResultType.Summary.TransactionSummaries }
         *     
         */
        public void setTransactionSummaries(TransactionSummaries value) {
            this.transactionSummaries = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PageSummary" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                 &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                 &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                 &lt;attribute name="pageCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="responseTime" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pageSummary"
        })
        public static class PageSummaries {

            @XmlElement(name = "PageSummary")
            protected List<PageSummary> pageSummary;

            /**
             * Gets the value of the pageSummary property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the pageSummary property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPageSummary().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link com.expedia.aggregator.data.LoadTestResultType.Summary.PageSummaries.PageSummary }
             * 
             * 
             */
            public List<PageSummary> getPageSummary() {
                if (pageSummary == null) {
                    pageSummary = new ArrayList<PageSummary>();
                }
                return this.pageSummary;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *       &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *       &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *       &lt;attribute name="pageCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="responseTime" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class PageSummary {

                @XmlAttribute(name = "scenarioName", required = true)
                @XmlSchemaType(name = "anySimpleType")
                protected String scenarioName;
                @XmlAttribute(name = "testName", required = true)
                @XmlSchemaType(name = "anySimpleType")
                protected String testName;
                @XmlAttribute(name = "url", required = true)
                @XmlSchemaType(name = "anySimpleType")
                protected String url;
                @XmlAttribute(name = "pageCount", required = true)
                protected int pageCount;
                @XmlAttribute(name = "responseTime", required = true)
                protected int responseTime;

                /**
                 * Gets the value of the scenarioName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getScenarioName() {
                    return scenarioName;
                }

                /**
                 * Sets the value of the scenarioName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setScenarioName(String value) {
                    this.scenarioName = value;
                }

                /**
                 * Gets the value of the testName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTestName() {
                    return testName;
                }

                /**
                 * Sets the value of the testName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTestName(String value) {
                    this.testName = value;
                }

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the pageCount property.
                 * 
                 */
                public int getPageCount() {
                    return pageCount;
                }

                /**
                 * Sets the value of the pageCount property.
                 * 
                 */
                public void setPageCount(int value) {
                    this.pageCount = value;
                }

                /**
                 * Gets the value of the responseTime property.
                 * 
                 */
                public int getResponseTime() {
                    return responseTime;
                }

                /**
                 * Sets the value of the responseTime property.
                 * 
                 */
                public void setResponseTime(int value) {
                    this.responseTime = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PerformanceCounterResult" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="machineName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="categoryName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="instanceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="counterName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="isOverallResultCounter" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
         *                 &lt;attribute name="higherIsBetter" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "performanceCounterResult"
        })
        public static class PerformanceCounterResults {

            @XmlElement(name = "PerformanceCounterResult")
            protected List<PerformanceCounterResult> performanceCounterResult;

            /**
             * Gets the value of the performanceCounterResult property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the performanceCounterResult property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPerformanceCounterResult().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link com.expedia.aggregator.data.LoadTestResultType.Summary.PerformanceCounterResults.PerformanceCounterResult }
             * 
             * 
             */
            public List<PerformanceCounterResult> getPerformanceCounterResult() {
                if (performanceCounterResult == null) {
                    performanceCounterResult = new ArrayList<PerformanceCounterResult>();
                }
                return this.performanceCounterResult;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="machineName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="categoryName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="instanceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="counterName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="isOverallResultCounter" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
             *       &lt;attribute name="higherIsBetter" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class PerformanceCounterResult {

                @XmlAttribute(name = "machineName", required = true)
                protected String machineName;
                @XmlAttribute(name = "categoryName", required = true)
                protected String categoryName;
                @XmlAttribute(name = "instanceName", required = true)
                protected String instanceName;
                @XmlAttribute(name = "counterName", required = true)
                protected String counterName;
                @XmlAttribute(name = "value", required = true)
                protected double value;
                @XmlAttribute(name = "isOverallResultCounter")
                protected Boolean isOverallResultCounter;
                @XmlAttribute(name = "higherIsBetter")
                protected Boolean higherIsBetter;

                /**
                 * Gets the value of the machineName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMachineName() {
                    return machineName;
                }

                /**
                 * Sets the value of the machineName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMachineName(String value) {
                    this.machineName = value;
                }

                /**
                 * Gets the value of the categoryName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCategoryName() {
                    return categoryName;
                }

                /**
                 * Sets the value of the categoryName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCategoryName(String value) {
                    this.categoryName = value;
                }

                /**
                 * Gets the value of the instanceName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInstanceName() {
                    return instanceName;
                }

                /**
                 * Sets the value of the instanceName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInstanceName(String value) {
                    this.instanceName = value;
                }

                /**
                 * Gets the value of the counterName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCounterName() {
                    return counterName;
                }

                /**
                 * Sets the value of the counterName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCounterName(String value) {
                    this.counterName = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public double getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(double value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the isOverallResultCounter property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public boolean isIsOverallResultCounter() {
                    if (isOverallResultCounter == null) {
                        return true;
                    } else {
                        return isOverallResultCounter;
                    }
                }

                /**
                 * Sets the value of the isOverallResultCounter property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setIsOverallResultCounter(Boolean value) {
                    this.isOverallResultCounter = value;
                }

                /**
                 * Gets the value of the higherIsBetter property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public boolean isHigherIsBetter() {
                    if (higherIsBetter == null) {
                        return true;
                    } else {
                        return higherIsBetter;
                    }
                }

                /**
                 * Sets the value of the higherIsBetter property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setHigherIsBetter(Boolean value) {
                    this.higherIsBetter = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TestSummary" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="totalTests" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="testsFailed" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="averageDuration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "testSummary"
        })
        public static class TestSummaries {

            @XmlElement(name = "TestSummary")
            protected List<TestSummary> testSummary;

            /**
             * Gets the value of the testSummary property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the testSummary property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTestSummary().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link com.expedia.aggregator.data.LoadTestResultType.Summary.TestSummaries.TestSummary }
             * 
             * 
             */
            public List<TestSummary> getTestSummary() {
                if (testSummary == null) {
                    testSummary = new ArrayList<TestSummary>();
                }
                return this.testSummary;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="totalTests" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="testsFailed" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="averageDuration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class TestSummary {

                @XmlAttribute(name = "scenarioName", required = true)
                protected String scenarioName;
                @XmlAttribute(name = "testName", required = true)
                protected String testName;
                @XmlAttribute(name = "totalTests", required = true)
                protected int totalTests;
                @XmlAttribute(name = "testsFailed", required = true)
                protected int testsFailed;
                @XmlAttribute(name = "averageDuration", required = true)
                protected int averageDuration;

                /**
                 * Gets the value of the scenarioName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getScenarioName() {
                    return scenarioName;
                }

                /**
                 * Sets the value of the scenarioName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setScenarioName(String value) {
                    this.scenarioName = value;
                }

                /**
                 * Gets the value of the testName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTestName() {
                    return testName;
                }

                /**
                 * Sets the value of the testName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTestName(String value) {
                    this.testName = value;
                }

                /**
                 * Gets the value of the totalTests property.
                 * 
                 */
                public int getTotalTests() {
                    return totalTests;
                }

                /**
                 * Sets the value of the totalTests property.
                 * 
                 */
                public void setTotalTests(int value) {
                    this.totalTests = value;
                }

                /**
                 * Gets the value of the testsFailed property.
                 * 
                 */
                public int getTestsFailed() {
                    return testsFailed;
                }

                /**
                 * Sets the value of the testsFailed property.
                 * 
                 */
                public void setTestsFailed(int value) {
                    this.testsFailed = value;
                }

                /**
                 * Gets the value of the averageDuration property.
                 * 
                 */
                public int getAverageDuration() {
                    return averageDuration;
                }

                /**
                 * Sets the value of the averageDuration property.
                 * 
                 */
                public void setAverageDuration(int value) {
                    this.averageDuration = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TransactionSummary" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="transactionName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="transactionCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="elapsedTime" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="responseTime" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "transactionSummary"
        })
        public static class TransactionSummaries {

            @XmlElement(name = "TransactionSummary")
            protected List<TransactionSummary> transactionSummary;

            /**
             * Gets the value of the transactionSummary property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the transactionSummary property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTransactionSummary().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link com.expedia.aggregator.data.LoadTestResultType.Summary.TransactionSummaries.TransactionSummary }
             * 
             * 
             */
            public List<TransactionSummary> getTransactionSummary() {
                if (transactionSummary == null) {
                    transactionSummary = new ArrayList<TransactionSummary>();
                }
                return this.transactionSummary;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="scenarioName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="testName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="transactionName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="transactionCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="elapsedTime" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="responseTime" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class TransactionSummary {

                @XmlAttribute(name = "scenarioName", required = true)
                protected String scenarioName;
                @XmlAttribute(name = "testName", required = true)
                protected String testName;
                @XmlAttribute(name = "transactionName", required = true)
                protected String transactionName;
                @XmlAttribute(name = "transactionCount", required = true)
                protected int transactionCount;
                @XmlAttribute(name = "elapsedTime", required = true)
                protected String elapsedTime;
                @XmlAttribute(name = "responseTime", required = true)
                protected String responseTime;

                /**
                 * Gets the value of the scenarioName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getScenarioName() {
                    return scenarioName;
                }

                /**
                 * Sets the value of the scenarioName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setScenarioName(String value) {
                    this.scenarioName = value;
                }

                /**
                 * Gets the value of the testName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTestName() {
                    return testName;
                }

                /**
                 * Sets the value of the testName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTestName(String value) {
                    this.testName = value;
                }

                /**
                 * Gets the value of the transactionName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTransactionName() {
                    return transactionName;
                }

                /**
                 * Sets the value of the transactionName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTransactionName(String value) {
                    this.transactionName = value;
                }

                /**
                 * Gets the value of the transactionCount property.
                 * 
                 */
                public int getTransactionCount() {
                    return transactionCount;
                }

                /**
                 * Sets the value of the transactionCount property.
                 * 
                 */
                public void setTransactionCount(int value) {
                    this.transactionCount = value;
                }

                /**
                 * Gets the value of the elapsedTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getElapsedTime() {
                    return elapsedTime;
                }

                /**
                 * Sets the value of the elapsedTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setElapsedTime(String value) {
                    this.elapsedTime = value;
                }

                /**
                 * Gets the value of the responseTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getResponseTime() {
                    return responseTime;
                }

                /**
                 * Sets the value of the responseTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setResponseTime(String value) {
                    this.responseTime = value;
                }

            }

        }

    }

}
