//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoadRunConfigurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoadRunConfigurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CounterSetMappings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CounterSetMapping" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CounterSetReferences">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CounterSetReference">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="counterSetName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="computerName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ContextParameters" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timingDetailsStorage" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="resultsStoreType" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *       &lt;attribute name="saveTestLogsOnError" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="saveTestLogsFrequency" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="maxErrorDetails" type="{http://www.w3.org/2001/XMLSchema}int" default="100" />
 *       &lt;attribute name="maxErrorsPerType" type="{http://www.w3.org/2001/XMLSchema}int" default="1000" />
 *       &lt;attribute name="maxThresholdViolations" type="{http://www.w3.org/2001/XMLSchema}int" default="1000" />
 *       &lt;attribute name="maxRequestUrlsReported" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="useTestIterations" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="runDuration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="warmupTime" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="coolDownTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="testIterations" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="webTestConnectionModel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="webTestConnectionPoolSize" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="sampleRate" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="validationLevel" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="sqlTracingConnectString" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sqlTracingConnectStringDisplayValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sqlTracingDirectory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sqlTracingEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="sqlTracingMinimumDuration" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="runUnitTestsInAppDomain" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoadRunConfigurationType", propOrder = {
    "counterSetMappings",
    "contextParameters"
})
public class LoadRunConfigurationType {

    @XmlElement(name = "CounterSetMappings", required = true)
    protected CounterSetMappings counterSetMappings;
    @XmlElement(name = "ContextParameters", required = true)
    protected Object contextParameters;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "timingDetailsStorage")
    protected Integer timingDetailsStorage;
    @XmlAttribute(name = "resultsStoreType")
    protected Integer resultsStoreType;
    @XmlAttribute(name = "saveTestLogsOnError")
    protected Boolean saveTestLogsOnError;
    @XmlAttribute(name = "saveTestLogsFrequency")
    protected Integer saveTestLogsFrequency;
    @XmlAttribute(name = "maxErrorDetails")
    protected Integer maxErrorDetails;
    @XmlAttribute(name = "maxErrorsPerType")
    protected Integer maxErrorsPerType;
    @XmlAttribute(name = "maxThresholdViolations")
    protected Integer maxThresholdViolations;
    @XmlAttribute(name = "maxRequestUrlsReported", required = true)
    protected int maxRequestUrlsReported;
    @XmlAttribute(name = "useTestIterations")
    protected Boolean useTestIterations;
    @XmlAttribute(name = "runDuration", required = true)
    protected int runDuration;
    @XmlAttribute(name = "warmupTime", required = true)
    protected int warmupTime;
    @XmlAttribute(name = "coolDownTime")
    protected Integer coolDownTime;
    @XmlAttribute(name = "testIterations")
    protected Integer testIterations;
    @XmlAttribute(name = "webTestConnectionModel")
    protected String webTestConnectionModel;
    @XmlAttribute(name = "webTestConnectionPoolSize")
    protected Integer webTestConnectionPoolSize;
    @XmlAttribute(name = "sampleRate", required = true)
    protected int sampleRate;
    @XmlAttribute(name = "validationLevel", required = true)
    protected int validationLevel;
    @XmlAttribute(name = "sqlTracingConnectString")
    protected String sqlTracingConnectString;
    @XmlAttribute(name = "sqlTracingConnectStringDisplayValue")
    protected String sqlTracingConnectStringDisplayValue;
    @XmlAttribute(name = "sqlTracingDirectory")
    protected String sqlTracingDirectory;
    @XmlAttribute(name = "sqlTracingEnabled")
    protected Boolean sqlTracingEnabled;
    @XmlAttribute(name = "sqlTracingMinimumDuration")
    protected Integer sqlTracingMinimumDuration;
    @XmlAttribute(name = "runUnitTestsInAppDomain")
    protected Boolean runUnitTestsInAppDomain;

    /**
     * Gets the value of the counterSetMappings property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.LoadRunConfigurationType.CounterSetMappings }
     *     
     */
    public CounterSetMappings getCounterSetMappings() {
        return counterSetMappings;
    }

    /**
     * Sets the value of the counterSetMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.LoadRunConfigurationType.CounterSetMappings }
     *     
     */
    public void setCounterSetMappings(CounterSetMappings value) {
        this.counterSetMappings = value;
    }

    /**
     * Gets the value of the contextParameters property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getContextParameters() {
        return contextParameters;
    }

    /**
     * Sets the value of the contextParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setContextParameters(Object value) {
        this.contextParameters = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the timingDetailsStorage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimingDetailsStorage() {
        return timingDetailsStorage;
    }

    /**
     * Sets the value of the timingDetailsStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimingDetailsStorage(Integer value) {
        this.timingDetailsStorage = value;
    }

    /**
     * Gets the value of the resultsStoreType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getResultsStoreType() {
        if (resultsStoreType == null) {
            return  1;
        } else {
            return resultsStoreType;
        }
    }

    /**
     * Sets the value of the resultsStoreType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResultsStoreType(Integer value) {
        this.resultsStoreType = value;
    }

    /**
     * Gets the value of the saveTestLogsOnError property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSaveTestLogsOnError() {
        return saveTestLogsOnError;
    }

    /**
     * Sets the value of the saveTestLogsOnError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSaveTestLogsOnError(Boolean value) {
        this.saveTestLogsOnError = value;
    }

    /**
     * Gets the value of the saveTestLogsFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSaveTestLogsFrequency() {
        if (saveTestLogsFrequency == null) {
            return  0;
        } else {
            return saveTestLogsFrequency;
        }
    }

    /**
     * Sets the value of the saveTestLogsFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSaveTestLogsFrequency(Integer value) {
        this.saveTestLogsFrequency = value;
    }

    /**
     * Gets the value of the maxErrorDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxErrorDetails() {
        if (maxErrorDetails == null) {
            return  100;
        } else {
            return maxErrorDetails;
        }
    }

    /**
     * Sets the value of the maxErrorDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxErrorDetails(Integer value) {
        this.maxErrorDetails = value;
    }

    /**
     * Gets the value of the maxErrorsPerType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxErrorsPerType() {
        if (maxErrorsPerType == null) {
            return  1000;
        } else {
            return maxErrorsPerType;
        }
    }

    /**
     * Sets the value of the maxErrorsPerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxErrorsPerType(Integer value) {
        this.maxErrorsPerType = value;
    }

    /**
     * Gets the value of the maxThresholdViolations property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxThresholdViolations() {
        if (maxThresholdViolations == null) {
            return  1000;
        } else {
            return maxThresholdViolations;
        }
    }

    /**
     * Sets the value of the maxThresholdViolations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxThresholdViolations(Integer value) {
        this.maxThresholdViolations = value;
    }

    /**
     * Gets the value of the maxRequestUrlsReported property.
     * 
     */
    public int getMaxRequestUrlsReported() {
        return maxRequestUrlsReported;
    }

    /**
     * Sets the value of the maxRequestUrlsReported property.
     * 
     */
    public void setMaxRequestUrlsReported(int value) {
        this.maxRequestUrlsReported = value;
    }

    /**
     * Gets the value of the useTestIterations property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseTestIterations() {
        return useTestIterations;
    }

    /**
     * Sets the value of the useTestIterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseTestIterations(Boolean value) {
        this.useTestIterations = value;
    }

    /**
     * Gets the value of the runDuration property.
     * 
     */
    public int getRunDuration() {
        return runDuration;
    }

    /**
     * Sets the value of the runDuration property.
     * 
     */
    public void setRunDuration(int value) {
        this.runDuration = value;
    }

    /**
     * Gets the value of the warmupTime property.
     * 
     */
    public int getWarmupTime() {
        return warmupTime;
    }

    /**
     * Sets the value of the warmupTime property.
     * 
     */
    public void setWarmupTime(int value) {
        this.warmupTime = value;
    }

    /**
     * Gets the value of the coolDownTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCoolDownTime() {
        return coolDownTime;
    }

    /**
     * Sets the value of the coolDownTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCoolDownTime(Integer value) {
        this.coolDownTime = value;
    }

    /**
     * Gets the value of the testIterations property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTestIterations() {
        return testIterations;
    }

    /**
     * Sets the value of the testIterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTestIterations(Integer value) {
        this.testIterations = value;
    }

    /**
     * Gets the value of the webTestConnectionModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebTestConnectionModel() {
        return webTestConnectionModel;
    }

    /**
     * Sets the value of the webTestConnectionModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebTestConnectionModel(String value) {
        this.webTestConnectionModel = value;
    }

    /**
     * Gets the value of the webTestConnectionPoolSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWebTestConnectionPoolSize() {
        return webTestConnectionPoolSize;
    }

    /**
     * Sets the value of the webTestConnectionPoolSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWebTestConnectionPoolSize(Integer value) {
        this.webTestConnectionPoolSize = value;
    }

    /**
     * Gets the value of the sampleRate property.
     * 
     */
    public int getSampleRate() {
        return sampleRate;
    }

    /**
     * Sets the value of the sampleRate property.
     * 
     */
    public void setSampleRate(int value) {
        this.sampleRate = value;
    }

    /**
     * Gets the value of the validationLevel property.
     * 
     */
    public int getValidationLevel() {
        return validationLevel;
    }

    /**
     * Sets the value of the validationLevel property.
     * 
     */
    public void setValidationLevel(int value) {
        this.validationLevel = value;
    }

    /**
     * Gets the value of the sqlTracingConnectString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqlTracingConnectString() {
        return sqlTracingConnectString;
    }

    /**
     * Sets the value of the sqlTracingConnectString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqlTracingConnectString(String value) {
        this.sqlTracingConnectString = value;
    }

    /**
     * Gets the value of the sqlTracingConnectStringDisplayValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqlTracingConnectStringDisplayValue() {
        return sqlTracingConnectStringDisplayValue;
    }

    /**
     * Sets the value of the sqlTracingConnectStringDisplayValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqlTracingConnectStringDisplayValue(String value) {
        this.sqlTracingConnectStringDisplayValue = value;
    }

    /**
     * Gets the value of the sqlTracingDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqlTracingDirectory() {
        return sqlTracingDirectory;
    }

    /**
     * Sets the value of the sqlTracingDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqlTracingDirectory(String value) {
        this.sqlTracingDirectory = value;
    }

    /**
     * Gets the value of the sqlTracingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSqlTracingEnabled() {
        return sqlTracingEnabled;
    }

    /**
     * Sets the value of the sqlTracingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSqlTracingEnabled(Boolean value) {
        this.sqlTracingEnabled = value;
    }

    /**
     * Gets the value of the sqlTracingMinimumDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSqlTracingMinimumDuration() {
        return sqlTracingMinimumDuration;
    }

    /**
     * Sets the value of the sqlTracingMinimumDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSqlTracingMinimumDuration(Integer value) {
        this.sqlTracingMinimumDuration = value;
    }

    /**
     * Gets the value of the runUnitTestsInAppDomain property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRunUnitTestsInAppDomain() {
        return runUnitTestsInAppDomain;
    }

    /**
     * Sets the value of the runUnitTestsInAppDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRunUnitTestsInAppDomain(Boolean value) {
        this.runUnitTestsInAppDomain = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CounterSetMapping" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CounterSetReferences">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CounterSetReference">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="counterSetName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="computerName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "counterSetMapping"
    })
    public static class CounterSetMappings {

        @XmlElement(name = "CounterSetMapping")
        protected List<CounterSetMapping> counterSetMapping;

        /**
         * Gets the value of the counterSetMapping property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the counterSetMapping property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCounterSetMapping().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.expedia.aggregator.data.LoadRunConfigurationType.CounterSetMappings.CounterSetMapping }
         * 
         * 
         */
        public List<CounterSetMapping> getCounterSetMapping() {
            if (counterSetMapping == null) {
                counterSetMapping = new ArrayList<CounterSetMapping>();
            }
            return this.counterSetMapping;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CounterSetReferences">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CounterSetReference">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="counterSetName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="computerName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "counterSetReferences"
        })
        public static class CounterSetMapping {

            @XmlElement(name = "CounterSetReferences", required = true)
            protected CounterSetReferences counterSetReferences;
            @XmlAttribute(name = "computerName", required = true)
            protected String computerName;

            /**
             * Gets the value of the counterSetReferences property.
             * 
             * @return
             *     possible object is
             *     {@link com.expedia.aggregator.data.LoadRunConfigurationType.CounterSetMappings.CounterSetMapping.CounterSetReferences }
             *     
             */
            public CounterSetReferences getCounterSetReferences() {
                return counterSetReferences;
            }

            /**
             * Sets the value of the counterSetReferences property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.expedia.aggregator.data.LoadRunConfigurationType.CounterSetMappings.CounterSetMapping.CounterSetReferences }
             *     
             */
            public void setCounterSetReferences(CounterSetReferences value) {
                this.counterSetReferences = value;
            }

            /**
             * Gets the value of the computerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComputerName() {
                return computerName;
            }

            /**
             * Sets the value of the computerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComputerName(String value) {
                this.computerName = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CounterSetReference">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="counterSetName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "counterSetReference"
            })
            public static class CounterSetReferences {

                @XmlElement(name = "CounterSetReference", required = true)
                protected CounterSetReference counterSetReference;

                /**
                 * Gets the value of the counterSetReference property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link com.expedia.aggregator.data.LoadRunConfigurationType.CounterSetMappings.CounterSetMapping.CounterSetReferences.CounterSetReference }
                 *     
                 */
                public CounterSetReference getCounterSetReference() {
                    return counterSetReference;
                }

                /**
                 * Sets the value of the counterSetReference property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link com.expedia.aggregator.data.LoadRunConfigurationType.CounterSetMappings.CounterSetMapping.CounterSetReferences.CounterSetReference }
                 *     
                 */
                public void setCounterSetReference(CounterSetReference value) {
                    this.counterSetReference = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="counterSetName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class CounterSetReference {

                    @XmlAttribute(name = "counterSetName")
                    @XmlSchemaType(name = "anySimpleType")
                    protected String counterSetName;

                    /**
                     * Gets the value of the counterSetName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCounterSetName() {
                        return counterSetName;
                    }

                    /**
                     * Sets the value of the counterSetName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCounterSetName(String value) {
                        this.counterSetName = value;
                    }

                }

            }

        }

    }

}
