//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderedTestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderedTestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}BaseTestType">
 *       &lt;sequence>
 *         &lt;element name="TestLinks" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}TestLinksType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="continueAfterFailure" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderedTestType", propOrder = {
    "testLinks"
})
public class OrderedTestType
    extends BaseTestType
{

    @XmlElement(name = "TestLinks")
    protected TestLinksType testLinks;
    @XmlAttribute(name = "continueAfterFailure")
    protected Boolean continueAfterFailure;

    /**
     * Gets the value of the testLinks property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.TestLinksType }
     *     
     */
    public TestLinksType getTestLinks() {
        return testLinks;
    }

    /**
     * Sets the value of the testLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.TestLinksType }
     *     
     */
    public void setTestLinks(TestLinksType value) {
        this.testLinks = value;
    }

    /**
     * Gets the value of the continueAfterFailure property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isContinueAfterFailure() {
        if (continueAfterFailure == null) {
            return false;
        } else {
            return continueAfterFailure;
        }
    }

    /**
     * Sets the value of the continueAfterFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContinueAfterFailure(Boolean value) {
        this.continueAfterFailure = value;
    }

}
