//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PanelLayoutType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PanelLayoutType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="One"/>
 *     &lt;enumeration value="TwoHorizontal"/>
 *     &lt;enumeration value="TwoVertical"/>
 *     &lt;enumeration value="ThreeLeft"/>
 *     &lt;enumeration value="ThreeRight"/>
 *     &lt;enumeration value="ThreeTop"/>
 *     &lt;enumeration value="ThreeBottom"/>
 *     &lt;enumeration value="ThreeHorizontal"/>
 *     &lt;enumeration value="ThreeVertical"/>
 *     &lt;enumeration value="FourHorizontal"/>
 *     &lt;enumeration value="FourVertical"/>
 *     &lt;enumeration value="FourGrid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PanelLayoutType")
@XmlEnum
public enum PanelLayoutType {

    @XmlEnumValue("One")
    ONE("One"),
    @XmlEnumValue("TwoHorizontal")
    TWO_HORIZONTAL("TwoHorizontal"),
    @XmlEnumValue("TwoVertical")
    TWO_VERTICAL("TwoVertical"),
    @XmlEnumValue("ThreeLeft")
    THREE_LEFT("ThreeLeft"),
    @XmlEnumValue("ThreeRight")
    THREE_RIGHT("ThreeRight"),
    @XmlEnumValue("ThreeTop")
    THREE_TOP("ThreeTop"),
    @XmlEnumValue("ThreeBottom")
    THREE_BOTTOM("ThreeBottom"),
    @XmlEnumValue("ThreeHorizontal")
    THREE_HORIZONTAL("ThreeHorizontal"),
    @XmlEnumValue("ThreeVertical")
    THREE_VERTICAL("ThreeVertical"),
    @XmlEnumValue("FourHorizontal")
    FOUR_HORIZONTAL("FourHorizontal"),
    @XmlEnumValue("FourVertical")
    FOUR_VERTICAL("FourVertical"),
    @XmlEnumValue("FourGrid")
    FOUR_GRID("FourGrid");
    private final String value;

    PanelLayoutType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PanelLayoutType fromValue(String v) {
        for (PanelLayoutType c: PanelLayoutType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
