//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParetoTrafficType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParetoTrafficType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}ExponentialTrafficType">
 *       &lt;sequence>
 *         &lt;element name="Shape" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParetoTrafficType", propOrder = {
    "shape"
})
public class ParetoTrafficType
    extends ExponentialTrafficType
{

    @XmlElement(name = "Shape")
    protected double shape;

    /**
     * Gets the value of the shape property.
     * 
     */
    public double getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     */
    public void setShape(double value) {
        this.shape = value;
    }

}
