//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RandomErrorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RandomErrorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ErrorUnit" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}ErrorUnitType"/>
 *         &lt;element name="Rate" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}PercentType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RandomErrorType", propOrder = {

})
public class RandomErrorType {

    @XmlElement(name = "ErrorUnit", required = true)
    protected ErrorUnitType errorUnit;
    @XmlElement(name = "Rate", required = true)
    protected BigDecimal rate;

    /**
     * Gets the value of the errorUnit property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.ErrorUnitType }
     *     
     */
    public ErrorUnitType getErrorUnit() {
        return errorUnit;
    }

    /**
     * Sets the value of the errorUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.ErrorUnitType }
     *     
     */
    public void setErrorUnit(ErrorUnitType value) {
        this.errorUnit = value;
    }

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public void setRate(BigDecimal value) {
        this.rate = value;
    }

}
