//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for RedQueueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RedQueueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}DropType"/>
 *         &lt;element name="QueueMode" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}UnitType"/>
 *         &lt;element name="MinPacket" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="MaxPacket" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="PacketSize" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RedQueueType", propOrder = {

})
public class RedQueueType {

    @XmlElement(name = "DropType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dropType;
    @XmlElement(name = "QueueMode", required = true)
    protected UnitType queueMode;
    @XmlElement(name = "MinPacket", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger minPacket;
    @XmlElement(name = "MaxPacket", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxPacket;
    @XmlElement(name = "PacketSize", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger packetSize;

    /**
     * Gets the value of the dropType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropType() {
        return dropType;
    }

    /**
     * Sets the value of the dropType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropType(String value) {
        this.dropType = value;
    }

    /**
     * Gets the value of the queueMode property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.UnitType }
     *     
     */
    public UnitType getQueueMode() {
        return queueMode;
    }

    /**
     * Sets the value of the queueMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.UnitType }
     *     
     */
    public void setQueueMode(UnitType value) {
        this.queueMode = value;
    }

    /**
     * Gets the value of the minPacket property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getMinPacket() {
        return minPacket;
    }

    /**
     * Sets the value of the minPacket property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setMinPacket(BigInteger value) {
        this.minPacket = value;
    }

    /**
     * Gets the value of the maxPacket property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getMaxPacket() {
        return maxPacket;
    }

    /**
     * Sets the value of the maxPacket property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setMaxPacket(BigInteger value) {
        this.maxPacket = value;
    }

    /**
     * Gets the value of the packetSize property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public BigInteger getPacketSize() {
        return packetSize;
    }

    /**
     * Sets the value of the packetSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setPacketSize(BigInteger value) {
        this.packetSize = value;
    }

}
