//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Normal" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}NormalReorderType"/>
 *         &lt;element name="Empirical1" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}Empirical1Type"/>
 *         &lt;element name="Empirical2" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}Empirical2Type"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "normal",
    "empirical1",
    "empirical2"
})
@XmlRootElement(name = "Reorder")
public class Reorder {

    @XmlElement(name = "Normal")
    protected NormalReorderType normal;
    @XmlElement(name = "Empirical1")
    protected Empirical1Type empirical1;
    @XmlElement(name = "Empirical2")
    protected Empirical2Type empirical2;

    /**
     * Gets the value of the normal property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.NormalReorderType }
     *     
     */
    public NormalReorderType getNormal() {
        return normal;
    }

    /**
     * Sets the value of the normal property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.NormalReorderType }
     *     
     */
    public void setNormal(NormalReorderType value) {
        this.normal = value;
    }

    /**
     * Gets the value of the empirical1 property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.Empirical1Type }
     *     
     */
    public Empirical1Type getEmpirical1() {
        return empirical1;
    }

    /**
     * Sets the value of the empirical1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.Empirical1Type }
     *     
     */
    public void setEmpirical1(Empirical1Type value) {
        this.empirical1 = value;
    }

    /**
     * Gets the value of the empirical2 property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.Empirical2Type }
     *     
     */
    public Empirical2Type getEmpirical2() {
        return empirical2;
    }

    /**
     * Sets the value of the empirical2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.Empirical2Type }
     *     
     */
    public void setEmpirical2(Empirical2Type value) {
        this.empirical2 = value;
    }

}
