//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for ResultsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="UnitTestResult" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}UnitTestResultType"/>
 *           &lt;element name="GenericTestResult" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}TestResultAggregationType"/>
 *           &lt;element name="TestResult" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}TestResultType"/>
 *           &lt;element name="ManualTestResult" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}ManualTestResultType"/>
 *           &lt;element name="TestResultAggregation" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}TestResultAggregationType"/>
 *           &lt;element name="WebTestResult" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}WebTestResultType"/>
 *           &lt;element name="LoadTestResult" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}LoadTestResultType"/>
 *           &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultsType", propOrder = {
    "unitTestResultOrGenericTestResultOrTestResult"
})
public class ResultsType {

    @XmlElementRefs({
        @XmlElementRef(name = "ManualTestResult", namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "UnitTestResult", namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TestResultAggregation", namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TestResult", namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "GenericTestResult", namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LoadTestResult", namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "WebTestResult", namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010", type = JAXBElement.class, required = false)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> unitTestResultOrGenericTestResultOrTestResult;

    /**
     * Gets the value of the unitTestResultOrGenericTestResultOrTestResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unitTestResultOrGenericTestResultOrTestResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnitTestResultOrGenericTestResultOrTestResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link com.expedia.aggregator.data.ManualTestResultType }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link com.expedia.aggregator.data.UnitTestResultType }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link com.expedia.aggregator.data.TestResultAggregationType }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link com.expedia.aggregator.data.TestResultType }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link com.expedia.aggregator.data.TestResultAggregationType }{@code >}
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link com.expedia.aggregator.data.LoadTestResultType }{@code >}
     * {@link org.w3c.dom.Element }
     * {@link javax.xml.bind.JAXBElement }{@code <}{@link com.expedia.aggregator.data.WebTestResultType }{@code >}
     * {@link Object }
     * 
     * 
     */
    public List<Object> getUnitTestResultOrGenericTestResultOrTestResult() {
        if (unitTestResultOrGenericTestResultOrTestResult == null) {
            unitTestResultOrGenericTestResultOrTestResult = new ArrayList<Object>();
        }
        return this.unitTestResultOrGenericTestResultOrTestResult;
    }

}
