//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RuntimeResolutionDirectoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RuntimeResolutionDirectoryType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}ResolutionDirectoryType">
 *       &lt;attribute name="useLoadContext" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuntimeResolutionDirectoryType")
public class RuntimeResolutionDirectoryType
    extends ResolutionDirectoryType
{

    @XmlAttribute(name = "useLoadContext")
    protected Boolean useLoadContext;

    /**
     * Gets the value of the useLoadContext property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseLoadContext() {
        return useLoadContext;
    }

    /**
     * Sets the value of the useLoadContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseLoadContext(Boolean value) {
        this.useLoadContext = value;
    }

}
