//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatisticalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatisticalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Good" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}PercentType"/>
 *         &lt;element name="GoodToBad" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}PercentType"/>
 *         &lt;element name="Bad" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}PercentType"/>
 *         &lt;element name="BadToGood" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}PercentType"/>
 *         &lt;element name="SwitchTime" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}SecType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatisticalType", propOrder = {
    "good",
    "goodToBad",
    "bad",
    "badToGood",
    "switchTime"
})
@XmlSeeAlso({
    StatisticalErrorType.class
})
public class StatisticalType {

    @XmlElement(name = "Good", required = true)
    protected BigDecimal good;
    @XmlElement(name = "GoodToBad", required = true)
    protected BigDecimal goodToBad;
    @XmlElement(name = "Bad", required = true)
    protected BigDecimal bad;
    @XmlElement(name = "BadToGood", required = true)
    protected BigDecimal badToGood;
    @XmlElement(name = "SwitchTime", required = true)
    protected SecType switchTime;

    /**
     * Gets the value of the good property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public BigDecimal getGood() {
        return good;
    }

    /**
     * Sets the value of the good property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public void setGood(BigDecimal value) {
        this.good = value;
    }

    /**
     * Gets the value of the goodToBad property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public BigDecimal getGoodToBad() {
        return goodToBad;
    }

    /**
     * Sets the value of the goodToBad property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public void setGoodToBad(BigDecimal value) {
        this.goodToBad = value;
    }

    /**
     * Gets the value of the bad property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public BigDecimal getBad() {
        return bad;
    }

    /**
     * Sets the value of the bad property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public void setBad(BigDecimal value) {
        this.bad = value;
    }

    /**
     * Gets the value of the badToGood property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public BigDecimal getBadToGood() {
        return badToGood;
    }

    /**
     * Sets the value of the badToGood property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public void setBadToGood(BigDecimal value) {
        this.badToGood = value;
    }

    /**
     * Gets the value of the switchTime property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.SecType }
     *     
     */
    public SecType getSwitchTime() {
        return switchTime;
    }

    /**
     * Sets the value of the switchTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.SecType }
     *     
     */
    public void setSwitchTime(SecType value) {
        this.switchTime = value;
    }

}
