//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatisticalErrorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatisticalErrorType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}StatisticalType">
 *       &lt;sequence>
 *         &lt;element name="ErrorUnit" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}ErrorUnitType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatisticalErrorType", propOrder = {
    "errorUnit"
})
public class StatisticalErrorType
    extends StatisticalType
{

    @XmlElement(name = "ErrorUnit", required = true)
    protected ErrorUnitType errorUnit;

    /**
     * Gets the value of the errorUnit property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.ErrorUnitType }
     *     
     */
    public ErrorUnitType getErrorUnit() {
        return errorUnit;
    }

    /**
     * Sets the value of the errorUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.ErrorUnitType }
     *     
     */
    public void setErrorUnit(ErrorUnitType value) {
        this.errorUnit = value;
    }

}
