//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TcmInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TcmInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="testCaseId" use="required" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}positiveInt" />
 *       &lt;attribute name="testRunId" use="required" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}positiveInt" />
 *       &lt;attribute name="testResultId" use="required" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}positiveInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TcmInformationType")
public class TcmInformationType {

    @XmlAttribute(name = "testCaseId", required = true)
    protected int testCaseId;
    @XmlAttribute(name = "testRunId", required = true)
    protected int testRunId;
    @XmlAttribute(name = "testResultId", required = true)
    protected int testResultId;

    /**
     * Gets the value of the testCaseId property.
     * 
     */
    public int getTestCaseId() {
        return testCaseId;
    }

    /**
     * Sets the value of the testCaseId property.
     * 
     */
    public void setTestCaseId(int value) {
        this.testCaseId = value;
    }

    /**
     * Gets the value of the testRunId property.
     * 
     */
    public int getTestRunId() {
        return testRunId;
    }

    /**
     * Sets the value of the testRunId property.
     * 
     */
    public void setTestRunId(int value) {
        this.testRunId = value;
    }

    /**
     * Gets the value of the testResultId property.
     * 
     */
    public int getTestResultId() {
        return testResultId;
    }

    /**
     * Sets the value of the testResultId property.
     * 
     */
    public void setTestResultId(int value) {
        this.testResultId = value;
    }

}
