//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestEntryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestEntryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TcmInformation" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}TcmInformationType" minOccurs="0"/>
 *         &lt;element name="TestEntries" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}TestEntriesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="testId" use="required" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}IDSimpleType" />
 *       &lt;attribute name="executionId" use="required" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}IDSimpleType" />
 *       &lt;attribute name="parentExecutionId" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}IDSimpleType" default="00000000-0000-0000-0000-000000000000" />
 *       &lt;attribute name="testListId" use="required" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}IDSimpleType" />
 *       &lt;attribute name="isTransparent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestEntryType", propOrder = {
    "tcmInformation",
    "testEntries"
})
public class TestEntryType {

    @XmlElement(name = "TcmInformation")
    protected TcmInformationType tcmInformation;
    @XmlElement(name = "TestEntries")
    protected TestEntriesType testEntries;
    @XmlAttribute(name = "testId", required = true)
    protected String testId;
    @XmlAttribute(name = "executionId", required = true)
    protected String executionId;
    @XmlAttribute(name = "parentExecutionId")
    protected String parentExecutionId;
    @XmlAttribute(name = "testListId", required = true)
    protected String testListId;
    @XmlAttribute(name = "isTransparent")
    protected Boolean isTransparent;

    /**
     * Gets the value of the tcmInformation property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.TcmInformationType }
     *     
     */
    public TcmInformationType getTcmInformation() {
        return tcmInformation;
    }

    /**
     * Sets the value of the tcmInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.TcmInformationType }
     *     
     */
    public void setTcmInformation(TcmInformationType value) {
        this.tcmInformation = value;
    }

    /**
     * Gets the value of the testEntries property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.TestEntriesType }
     *     
     */
    public TestEntriesType getTestEntries() {
        return testEntries;
    }

    /**
     * Sets the value of the testEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.TestEntriesType }
     *     
     */
    public void setTestEntries(TestEntriesType value) {
        this.testEntries = value;
    }

    /**
     * Gets the value of the testId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestId() {
        return testId;
    }

    /**
     * Sets the value of the testId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestId(String value) {
        this.testId = value;
    }

    /**
     * Gets the value of the executionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * Sets the value of the executionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecutionId(String value) {
        this.executionId = value;
    }

    /**
     * Gets the value of the parentExecutionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentExecutionId() {
        if (parentExecutionId == null) {
            return "00000000-0000-0000-0000-000000000000";
        } else {
            return parentExecutionId;
        }
    }

    /**
     * Sets the value of the parentExecutionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentExecutionId(String value) {
        this.parentExecutionId = value;
    }

    /**
     * Gets the value of the testListId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestListId() {
        return testListId;
    }

    /**
     * Sets the value of the testListId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestListId(String value) {
        this.testListId = value;
    }

    /**
     * Gets the value of the isTransparent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsTransparent() {
        if (isTransparent == null) {
            return true;
        } else {
            return isTransparent;
        }
    }

    /**
     * Sets the value of the isTransparent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTransparent(Boolean value) {
        this.isTransparent = value;
    }

}
