//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestRunOutputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestRunOutputType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all minOccurs="0">
 *         &lt;element name="StdOut" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="StdErr" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="DebugTrace" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="TraceInfo" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestRunOutputType", propOrder = {

})
public class TestRunOutputType {

    @XmlElement(name = "StdOut")
    protected Object stdOut;
    @XmlElement(name = "StdErr")
    protected Object stdErr;
    @XmlElement(name = "DebugTrace")
    protected Object debugTrace;
    @XmlElement(name = "TraceInfo")
    protected Object traceInfo;

    /**
     * Gets the value of the stdOut property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStdOut() {
        return stdOut;
    }

    /**
     * Sets the value of the stdOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStdOut(Object value) {
        this.stdOut = value;
    }

    /**
     * Gets the value of the stdErr property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStdErr() {
        return stdErr;
    }

    /**
     * Sets the value of the stdErr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStdErr(Object value) {
        this.stdErr = value;
    }

    /**
     * Gets the value of the debugTrace property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDebugTrace() {
        return debugTrace;
    }

    /**
     * Sets the value of the debugTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDebugTrace(Object value) {
        this.debugTrace = value;
    }

    /**
     * Gets the value of the traceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTraceInfo() {
        return traceInfo;
    }

    /**
     * Sets the value of the traceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTraceInfo(Object value) {
        this.traceInfo = value;
    }

}
