//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UniformLatencyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UniformLatencyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Min" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}MsecType"/>
 *         &lt;element name="Max" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}MsecType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UniformLatencyType", propOrder = {
    "min",
    "max"
})
@XmlSeeAlso({
    LinearLatencyType.class
})
public class UniformLatencyType {

    @XmlElement(name = "Min", required = true)
    protected MsecType min;
    @XmlElement(name = "Max", required = true)
    protected MsecType max;

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.MsecType }
     *     
     */
    public MsecType getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.MsecType }
     *     
     */
    public void setMin(MsecType value) {
        this.min = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.MsecType }
     *     
     */
    public MsecType getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.MsecType }
     *     
     */
    public void setMax(MsecType value) {
        this.max = value;
    }

}
