//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for UnitTestResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnitTestResultType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}TestResultAggregationType">
 *       &lt;sequence>
 *         &lt;element name="ExtensionResult" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;any processContents='lax' namespace='##other'/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="resultType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dataRowInfo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hasSufficientAccess" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnitTestResultType", propOrder = {
    "extensionResult"
})
public class UnitTestResultType
    extends TestResultAggregationType
{

    @XmlElement(name = "ExtensionResult")
    protected ExtensionResult extensionResult;
    @XmlAttribute(name = "resultType")
    protected String resultType;
    @XmlAttribute(name = "dataRowInfo")
    protected String dataRowInfo;
    @XmlAttribute(name = "hasSufficientAccess")
    protected Boolean hasSufficientAccess;

    /**
     * Gets the value of the extensionResult property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.UnitTestResultType.ExtensionResult }
     *     
     */
    public ExtensionResult getExtensionResult() {
        return extensionResult;
    }

    /**
     * Sets the value of the extensionResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.UnitTestResultType.ExtensionResult }
     *     
     */
    public void setExtensionResult(ExtensionResult value) {
        this.extensionResult = value;
    }

    /**
     * Gets the value of the resultType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultType() {
        return resultType;
    }

    /**
     * Sets the value of the resultType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultType(String value) {
        this.resultType = value;
    }

    /**
     * Gets the value of the dataRowInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRowInfo() {
        return dataRowInfo;
    }

    /**
     * Sets the value of the dataRowInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRowInfo(String value) {
        this.dataRowInfo = value;
    }

    /**
     * Gets the value of the hasSufficientAccess property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHasSufficientAccess() {
        if (hasSufficientAccess == null) {
            return true;
        } else {
            return hasSufficientAccess;
        }
    }

    /**
     * Sets the value of the hasSufficientAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasSufficientAccess(Boolean value) {
        this.hasSufficientAccess = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;any processContents='lax' namespace='##other'/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class ExtensionResult {

        @XmlMixed
        @XmlAnyElement(lax = true)
        protected List<Object> content;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * {@link org.w3c.dom.Element }
         * {@link Object }
         * 
         * 
         */
        public List<Object> getContent() {
            if (content == null) {
                content = new ArrayList<Object>();
            }
            return this.content;
        }

    }

}
