//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for UnitTestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnitTestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}BaseTestType">
 *       &lt;sequence>
 *         &lt;element name="TestMethod">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="codeBase" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="className" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="isValid" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="adapterTypeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DataSource" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="settingName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="accessMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="connectionString" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="providerInvariantName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="tableName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AspNet" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DevelopmentServer" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}DevelopmentServerType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="webSiteUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AspNetDevelopmentServers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DevelopmentServer" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Extension" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;any processContents='lax' namespace='##other'/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnitTestType", propOrder = {
    "testMethod",
    "dataSource",
    "aspNet",
    "aspNetDevelopmentServers",
    "extension"
})
public class UnitTestType
    extends BaseTestType
{

    @XmlElement(name = "TestMethod", required = true)
    protected TestMethod testMethod;
    @XmlElement(name = "DataSource")
    protected DataSource dataSource;
    @XmlElement(name = "AspNet")
    protected AspNet aspNet;
    @XmlElement(name = "AspNetDevelopmentServers")
    protected AspNetDevelopmentServers aspNetDevelopmentServers;
    @XmlElement(name = "Extension")
    protected Extension extension;

    /**
     * Gets the value of the testMethod property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.UnitTestType.TestMethod }
     *     
     */
    public TestMethod getTestMethod() {
        return testMethod;
    }

    /**
     * Sets the value of the testMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.UnitTestType.TestMethod }
     *     
     */
    public void setTestMethod(TestMethod value) {
        this.testMethod = value;
    }

    /**
     * Gets the value of the dataSource property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.UnitTestType.DataSource }
     *     
     */
    public DataSource getDataSource() {
        return dataSource;
    }

    /**
     * Sets the value of the dataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.UnitTestType.DataSource }
     *     
     */
    public void setDataSource(DataSource value) {
        this.dataSource = value;
    }

    /**
     * Gets the value of the aspNet property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.UnitTestType.AspNet }
     *     
     */
    public AspNet getAspNet() {
        return aspNet;
    }

    /**
     * Sets the value of the aspNet property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.UnitTestType.AspNet }
     *     
     */
    public void setAspNet(AspNet value) {
        this.aspNet = value;
    }

    /**
     * Gets the value of the aspNetDevelopmentServers property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.UnitTestType.AspNetDevelopmentServers }
     *     
     */
    public AspNetDevelopmentServers getAspNetDevelopmentServers() {
        return aspNetDevelopmentServers;
    }

    /**
     * Sets the value of the aspNetDevelopmentServers property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.UnitTestType.AspNetDevelopmentServers }
     *     
     */
    public void setAspNetDevelopmentServers(AspNetDevelopmentServers value) {
        this.aspNetDevelopmentServers = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.UnitTestType.Extension }
     *     
     */
    public Extension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.UnitTestType.Extension }
     *     
     */
    public void setExtension(Extension value) {
        this.extension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DevelopmentServer" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}DevelopmentServerType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="webSiteUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "developmentServer"
    })
    public static class AspNet {

        @XmlElement(name = "DevelopmentServer")
        protected List<DevelopmentServerType> developmentServer;
        @XmlAttribute(name = "webSiteUrl")
        protected String webSiteUrl;

        /**
         * Gets the value of the developmentServer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the developmentServer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDevelopmentServer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.expedia.aggregator.data.DevelopmentServerType }
         * 
         * 
         */
        public List<DevelopmentServerType> getDevelopmentServer() {
            if (developmentServer == null) {
                developmentServer = new ArrayList<DevelopmentServerType>();
            }
            return this.developmentServer;
        }

        /**
         * Gets the value of the webSiteUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWebSiteUrl() {
            return webSiteUrl;
        }

        /**
         * Sets the value of the webSiteUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWebSiteUrl(String value) {
            this.webSiteUrl = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DevelopmentServer" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "developmentServer"
    })
    public static class AspNetDevelopmentServers {

        @XmlElement(name = "DevelopmentServer")
        protected List<Object> developmentServer;

        /**
         * Gets the value of the developmentServer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the developmentServer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDevelopmentServer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getDevelopmentServer() {
            if (developmentServer == null) {
                developmentServer = new ArrayList<Object>();
            }
            return this.developmentServer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="settingName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="accessMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="connectionString" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="providerInvariantName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="tableName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DataSource {

        @XmlAttribute(name = "settingName")
        protected String settingName;
        @XmlAttribute(name = "accessMethod")
        protected String accessMethod;
        @XmlAttribute(name = "connectionString")
        protected String connectionString;
        @XmlAttribute(name = "providerInvariantName")
        protected String providerInvariantName;
        @XmlAttribute(name = "tableName")
        protected String tableName;

        /**
         * Gets the value of the settingName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSettingName() {
            return settingName;
        }

        /**
         * Sets the value of the settingName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSettingName(String value) {
            this.settingName = value;
        }

        /**
         * Gets the value of the accessMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessMethod() {
            return accessMethod;
        }

        /**
         * Sets the value of the accessMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessMethod(String value) {
            this.accessMethod = value;
        }

        /**
         * Gets the value of the connectionString property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConnectionString() {
            return connectionString;
        }

        /**
         * Sets the value of the connectionString property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConnectionString(String value) {
            this.connectionString = value;
        }

        /**
         * Gets the value of the providerInvariantName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProviderInvariantName() {
            return providerInvariantName;
        }

        /**
         * Sets the value of the providerInvariantName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProviderInvariantName(String value) {
            this.providerInvariantName = value;
        }

        /**
         * Gets the value of the tableName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTableName() {
            return tableName;
        }

        /**
         * Sets the value of the tableName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTableName(String value) {
            this.tableName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;any processContents='lax' namespace='##other'/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Extension {

        @XmlMixed
        @XmlAnyElement(lax = true)
        protected List<Object> content;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * {@link org.w3c.dom.Element }
         * {@link Object }
         * 
         * 
         */
        public List<Object> getContent() {
            if (content == null) {
                content = new ArrayList<Object>();
            }
            return this.content;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="codeBase" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="className" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="isValid" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;attribute name="adapterTypeName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TestMethod {

        @XmlAttribute(name = "codeBase", required = true)
        protected String codeBase;
        @XmlAttribute(name = "className", required = true)
        protected String className;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "isValid")
        protected Boolean isValid;
        @XmlAttribute(name = "adapterTypeName")
        protected String adapterTypeName;

        /**
         * Gets the value of the codeBase property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeBase() {
            return codeBase;
        }

        /**
         * Sets the value of the codeBase property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeBase(String value) {
            this.codeBase = value;
        }

        /**
         * Gets the value of the className property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClassName() {
            return className;
        }

        /**
         * Sets the value of the className property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClassName(String value) {
            this.className = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the isValid property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isIsValid() {
            if (isValid == null) {
                return false;
            } else {
                return isValid;
            }
        }

        /**
         * Sets the value of the isValid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIsValid(Boolean value) {
            this.isValid = value;
        }

        /**
         * Gets the value of the adapterTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdapterTypeName() {
            return adapterTypeName;
        }

        /**
         * Sets the value of the adapterTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdapterTypeName(String value) {
            this.adapterTypeName = value;
        }

    }

}
