//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebRequestResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WebRequestResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Request">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Headers" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="command" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="contentType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="encoding" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Response">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Headers" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="contentType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="statusLine" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="pageTime" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="statusCodeString" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="contentLength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Context" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Entry" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Errors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Error" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="StackTrace" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                             &lt;element name="ExceptionText" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}WebTestErrorType" />
 *                           &lt;attribute name="subType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DependantResults" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}WebRequestResultsType" minOccurs="0"/>
 *         &lt;element name="ValidationRuleResults" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ValidationRuleResult" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}RuleResultType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExtractionRuleResults" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ExtractionRuleResult" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}RuleResultType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="redirectUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="exceptionMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="run" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="submitted" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="cached" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isRedirectFollow" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="requestBodyBytesHandle" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="responseBytesHandle" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="resultsUrl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="httpStatus" type="{http://www.w3.org/2001/XMLSchema}int" default="200" />
 *       &lt;attribute name="recordResult" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="scenarioName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="testCaseName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="failedValidationRuleCount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="successfulExtractionRuleCount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="failedExtractionRuleCount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="requestPassedByCode" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebRequestResultType", propOrder = {
    "request",
    "response",
    "context",
    "errors",
    "dependantResults",
    "validationRuleResults",
    "extractionRuleResults"
})
public class WebRequestResultType {

    @XmlElement(name = "Request", required = true)
    protected Request request;
    @XmlElement(name = "Response", required = true)
    protected Response response;
    @XmlElement(name = "Context")
    protected Context context;
    @XmlElement(name = "Errors")
    protected Errors errors;
    @XmlElement(name = "DependantResults")
    protected WebRequestResultsType dependantResults;
    @XmlElement(name = "ValidationRuleResults")
    protected ValidationRuleResults validationRuleResults;
    @XmlElement(name = "ExtractionRuleResults")
    protected ExtractionRuleResults extractionRuleResults;
    @XmlAttribute(name = "redirectUrl")
    protected String redirectUrl;
    @XmlAttribute(name = "exceptionMessage")
    protected String exceptionMessage;
    @XmlAttribute(name = "run")
    protected Integer run;
    @XmlAttribute(name = "submitted")
    protected Boolean submitted;
    @XmlAttribute(name = "cached")
    protected Boolean cached;
    @XmlAttribute(name = "isRedirectFollow")
    protected Boolean isRedirectFollow;
    @XmlAttribute(name = "requestBodyBytesHandle")
    protected Integer requestBodyBytesHandle;
    @XmlAttribute(name = "responseBytesHandle")
    protected Integer responseBytesHandle;
    @XmlAttribute(name = "resultsUrl")
    protected String resultsUrl;
    @XmlAttribute(name = "httpStatus")
    protected Integer httpStatus;
    @XmlAttribute(name = "recordResult")
    protected Boolean recordResult;
    @XmlAttribute(name = "scenarioName")
    protected String scenarioName;
    @XmlAttribute(name = "testCaseName")
    protected String testCaseName;
    @XmlAttribute(name = "failedValidationRuleCount")
    protected Integer failedValidationRuleCount;
    @XmlAttribute(name = "successfulExtractionRuleCount")
    protected Integer successfulExtractionRuleCount;
    @XmlAttribute(name = "failedExtractionRuleCount")
    protected Integer failedExtractionRuleCount;
    @XmlAttribute(name = "requestPassedByCode")
    protected Boolean requestPassedByCode;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.Request }
     *     
     */
    public Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.Request }
     *     
     */
    public void setRequest(Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.Response }
     *     
     */
    public Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.Response }
     *     
     */
    public void setResponse(Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.Context }
     *     
     */
    public Context getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.Context }
     *     
     */
    public void setContext(Context value) {
        this.context = value;
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.Errors }
     *     
     */
    public Errors getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.Errors }
     *     
     */
    public void setErrors(Errors value) {
        this.errors = value;
    }

    /**
     * Gets the value of the dependantResults property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.WebRequestResultsType }
     *     
     */
    public WebRequestResultsType getDependantResults() {
        return dependantResults;
    }

    /**
     * Sets the value of the dependantResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.WebRequestResultsType }
     *     
     */
    public void setDependantResults(WebRequestResultsType value) {
        this.dependantResults = value;
    }

    /**
     * Gets the value of the validationRuleResults property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.ValidationRuleResults }
     *     
     */
    public ValidationRuleResults getValidationRuleResults() {
        return validationRuleResults;
    }

    /**
     * Sets the value of the validationRuleResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.ValidationRuleResults }
     *     
     */
    public void setValidationRuleResults(ValidationRuleResults value) {
        this.validationRuleResults = value;
    }

    /**
     * Gets the value of the extractionRuleResults property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.ExtractionRuleResults }
     *     
     */
    public ExtractionRuleResults getExtractionRuleResults() {
        return extractionRuleResults;
    }

    /**
     * Sets the value of the extractionRuleResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType.ExtractionRuleResults }
     *     
     */
    public void setExtractionRuleResults(ExtractionRuleResults value) {
        this.extractionRuleResults = value;
    }

    /**
     * Gets the value of the redirectUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * Sets the value of the redirectUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedirectUrl(String value) {
        this.redirectUrl = value;
    }

    /**
     * Gets the value of the exceptionMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExceptionMessage() {
        return exceptionMessage;
    }

    /**
     * Sets the value of the exceptionMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExceptionMessage(String value) {
        this.exceptionMessage = value;
    }

    /**
     * Gets the value of the run property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRun() {
        return run;
    }

    /**
     * Sets the value of the run property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRun(Integer value) {
        this.run = value;
    }

    /**
     * Gets the value of the submitted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSubmitted() {
        return submitted;
    }

    /**
     * Sets the value of the submitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSubmitted(Boolean value) {
        this.submitted = value;
    }

    /**
     * Gets the value of the cached property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCached() {
        return cached;
    }

    /**
     * Sets the value of the cached property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCached(Boolean value) {
        this.cached = value;
    }

    /**
     * Gets the value of the isRedirectFollow property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRedirectFollow() {
        return isRedirectFollow;
    }

    /**
     * Sets the value of the isRedirectFollow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRedirectFollow(Boolean value) {
        this.isRedirectFollow = value;
    }

    /**
     * Gets the value of the requestBodyBytesHandle property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRequestBodyBytesHandle() {
        return requestBodyBytesHandle;
    }

    /**
     * Sets the value of the requestBodyBytesHandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequestBodyBytesHandle(Integer value) {
        this.requestBodyBytesHandle = value;
    }

    /**
     * Gets the value of the responseBytesHandle property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getResponseBytesHandle() {
        return responseBytesHandle;
    }

    /**
     * Sets the value of the responseBytesHandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResponseBytesHandle(Integer value) {
        this.responseBytesHandle = value;
    }

    /**
     * Gets the value of the resultsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultsUrl() {
        return resultsUrl;
    }

    /**
     * Sets the value of the resultsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultsUrl(String value) {
        this.resultsUrl = value;
    }

    /**
     * Gets the value of the httpStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getHttpStatus() {
        if (httpStatus == null) {
            return  200;
        } else {
            return httpStatus;
        }
    }

    /**
     * Sets the value of the httpStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHttpStatus(Integer value) {
        this.httpStatus = value;
    }

    /**
     * Gets the value of the recordResult property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRecordResult() {
        if (recordResult == null) {
            return false;
        } else {
            return recordResult;
        }
    }

    /**
     * Sets the value of the recordResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRecordResult(Boolean value) {
        this.recordResult = value;
    }

    /**
     * Gets the value of the scenarioName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScenarioName() {
        return scenarioName;
    }

    /**
     * Sets the value of the scenarioName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScenarioName(String value) {
        this.scenarioName = value;
    }

    /**
     * Gets the value of the testCaseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestCaseName() {
        return testCaseName;
    }

    /**
     * Sets the value of the testCaseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestCaseName(String value) {
        this.testCaseName = value;
    }

    /**
     * Gets the value of the failedValidationRuleCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFailedValidationRuleCount() {
        return failedValidationRuleCount;
    }

    /**
     * Sets the value of the failedValidationRuleCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFailedValidationRuleCount(Integer value) {
        this.failedValidationRuleCount = value;
    }

    /**
     * Gets the value of the successfulExtractionRuleCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSuccessfulExtractionRuleCount() {
        return successfulExtractionRuleCount;
    }

    /**
     * Sets the value of the successfulExtractionRuleCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSuccessfulExtractionRuleCount(Integer value) {
        this.successfulExtractionRuleCount = value;
    }

    /**
     * Gets the value of the failedExtractionRuleCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFailedExtractionRuleCount() {
        return failedExtractionRuleCount;
    }

    /**
     * Sets the value of the failedExtractionRuleCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFailedExtractionRuleCount(Integer value) {
        this.failedExtractionRuleCount = value;
    }

    /**
     * Gets the value of the requestPassedByCode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestPassedByCode() {
        return requestPassedByCode;
    }

    /**
     * Sets the value of the requestPassedByCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestPassedByCode(Boolean value) {
        this.requestPassedByCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Entry" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry"
    })
    public static class Context {

        @XmlElement(name = "Entry")
        protected List<Entry> entry;

        /**
         * Gets the value of the entry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.expedia.aggregator.data.WebRequestResultType.Context.Entry }
         * 
         * 
         */
        public List<Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<Entry>();
            }
            return this.entry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Entry {

            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "value", required = true)
            protected String value;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Error" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="StackTrace" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                   &lt;element name="ExceptionText" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="type" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}WebTestErrorType" />
     *                 &lt;attribute name="subType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "error"
    })
    public static class Errors {

        @XmlElement(name = "Error")
        protected List<Error> error;

        /**
         * Gets the value of the error property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the error property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getError().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.expedia.aggregator.data.WebRequestResultType.Errors.Error }
         * 
         * 
         */
        public List<Error> getError() {
            if (error == null) {
                error = new ArrayList<Error>();
            }
            return this.error;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="StackTrace" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *         &lt;element name="ExceptionText" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="type" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}WebTestErrorType" />
         *       &lt;attribute name="subType" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "stackTrace",
            "exceptionText"
        })
        public static class Error {

            @XmlElement(name = "StackTrace")
            protected Object stackTrace;
            @XmlElement(name = "ExceptionText")
            protected Object exceptionText;
            @XmlAttribute(name = "type")
            protected WebTestErrorType type;
            @XmlAttribute(name = "subType")
            protected String subType;
            @XmlAttribute(name = "text", required = true)
            protected String text;
            @XmlAttribute(name = "time")
            protected String time;

            /**
             * Gets the value of the stackTrace property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getStackTrace() {
                return stackTrace;
            }

            /**
             * Sets the value of the stackTrace property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setStackTrace(Object value) {
                this.stackTrace = value;
            }

            /**
             * Gets the value of the exceptionText property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getExceptionText() {
                return exceptionText;
            }

            /**
             * Sets the value of the exceptionText property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setExceptionText(Object value) {
                this.exceptionText = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link com.expedia.aggregator.data.WebTestErrorType }
             *     
             */
            public WebTestErrorType getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.expedia.aggregator.data.WebTestErrorType }
             *     
             */
            public void setType(WebTestErrorType value) {
                this.type = value;
            }

            /**
             * Gets the value of the subType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubType() {
                return subType;
            }

            /**
             * Sets the value of the subType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubType(String value) {
                this.subType = value;
            }

            /**
             * Gets the value of the text property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getText() {
                return text;
            }

            /**
             * Sets the value of the text property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setText(String value) {
                this.text = value;
            }

            /**
             * Gets the value of the time property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTime() {
                return time;
            }

            /**
             * Sets the value of the time property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTime(String value) {
                this.time = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ExtractionRuleResult" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}RuleResultType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "extractionRuleResult"
    })
    public static class ExtractionRuleResults {

        @XmlElement(name = "ExtractionRuleResult")
        protected List<RuleResultType> extractionRuleResult;

        /**
         * Gets the value of the extractionRuleResult property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the extractionRuleResult property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExtractionRuleResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.expedia.aggregator.data.RuleResultType }
         * 
         * 
         */
        public List<RuleResultType> getExtractionRuleResult() {
            if (extractionRuleResult == null) {
                extractionRuleResult = new ArrayList<RuleResultType>();
            }
            return this.extractionRuleResult;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Headers" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="command" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="contentType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="encoding" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "headers"
    })
    public static class Request {

        @XmlElement(name = "Headers")
        protected Object headers;
        @XmlAttribute(name = "url")
        @XmlSchemaType(name = "anySimpleType")
        protected String url;
        @XmlAttribute(name = "command")
        @XmlSchemaType(name = "anySimpleType")
        protected String command;
        @XmlAttribute(name = "contentType")
        @XmlSchemaType(name = "anySimpleType")
        protected String contentType;
        @XmlAttribute(name = "encoding")
        @XmlSchemaType(name = "anySimpleType")
        protected String encoding;

        /**
         * Gets the value of the headers property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getHeaders() {
            return headers;
        }

        /**
         * Sets the value of the headers property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setHeaders(Object value) {
            this.headers = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the command property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCommand() {
            return command;
        }

        /**
         * Sets the value of the command property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCommand(String value) {
            this.command = value;
        }

        /**
         * Gets the value of the contentType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContentType() {
            return contentType;
        }

        /**
         * Sets the value of the contentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContentType(String value) {
            this.contentType = value;
        }

        /**
         * Gets the value of the encoding property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEncoding() {
            return encoding;
        }

        /**
         * Sets the value of the encoding property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEncoding(String value) {
            this.encoding = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Headers" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="contentType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="statusLine" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="pageTime" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="statusCodeString" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="contentLength" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "headers"
    })
    public static class Response {

        @XmlElement(name = "Headers")
        protected Object headers;
        @XmlAttribute(name = "url")
        @XmlSchemaType(name = "anySimpleType")
        protected String url;
        @XmlAttribute(name = "contentType")
        @XmlSchemaType(name = "anySimpleType")
        protected String contentType;
        @XmlAttribute(name = "statusLine")
        @XmlSchemaType(name = "anySimpleType")
        protected String statusLine;
        @XmlAttribute(name = "pageTime")
        @XmlSchemaType(name = "anySimpleType")
        protected String pageTime;
        @XmlAttribute(name = "time")
        @XmlSchemaType(name = "anySimpleType")
        protected String time;
        @XmlAttribute(name = "statusCodeString")
        protected String statusCodeString;
        @XmlAttribute(name = "contentLength")
        protected String contentLength;

        /**
         * Gets the value of the headers property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getHeaders() {
            return headers;
        }

        /**
         * Sets the value of the headers property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setHeaders(Object value) {
            this.headers = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the contentType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContentType() {
            return contentType;
        }

        /**
         * Sets the value of the contentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContentType(String value) {
            this.contentType = value;
        }

        /**
         * Gets the value of the statusLine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatusLine() {
            return statusLine;
        }

        /**
         * Sets the value of the statusLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatusLine(String value) {
            this.statusLine = value;
        }

        /**
         * Gets the value of the pageTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPageTime() {
            return pageTime;
        }

        /**
         * Sets the value of the pageTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPageTime(String value) {
            this.pageTime = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTime(String value) {
            this.time = value;
        }

        /**
         * Gets the value of the statusCodeString property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatusCodeString() {
            return statusCodeString;
        }

        /**
         * Sets the value of the statusCodeString property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatusCodeString(String value) {
            this.statusCodeString = value;
        }

        /**
         * Gets the value of the contentLength property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContentLength() {
            return contentLength;
        }

        /**
         * Sets the value of the contentLength property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContentLength(String value) {
            this.contentLength = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ValidationRuleResult" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}RuleResultType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "validationRuleResult"
    })
    public static class ValidationRuleResults {

        @XmlElement(name = "ValidationRuleResult")
        protected List<RuleResultType> validationRuleResult;

        /**
         * Gets the value of the validationRuleResult property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the validationRuleResult property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValidationRuleResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.expedia.aggregator.data.RuleResultType }
         * 
         * 
         */
        public List<RuleResultType> getValidationRuleResult() {
            if (validationRuleResult == null) {
                validationRuleResult = new ArrayList<RuleResultType>();
            }
            return this.validationRuleResult;
        }

    }

}
