//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebTestResultGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WebTestResultGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="WebTestResultComment" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}WebTestResultCommentType"/>
 *         &lt;element name="WebTestResultTransaction" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}WebTestResultTransactionType"/>
 *         &lt;element name="WebTestResultPage" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}WebTestResultPageType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebTestResultGroupType", propOrder = {
    "webTestResultCommentOrWebTestResultTransactionOrWebTestResultPage"
})
public class WebTestResultGroupType {

    @XmlElements({
        @XmlElement(name = "WebTestResultComment", type = WebTestResultCommentType.class),
        @XmlElement(name = "WebTestResultTransaction", type = WebTestResultTransactionType.class),
        @XmlElement(name = "WebTestResultPage", type = WebTestResultPageType.class)
    })
    protected List<Object> webTestResultCommentOrWebTestResultTransactionOrWebTestResultPage;

    /**
     * Gets the value of the webTestResultCommentOrWebTestResultTransactionOrWebTestResultPage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the webTestResultCommentOrWebTestResultTransactionOrWebTestResultPage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWebTestResultCommentOrWebTestResultTransactionOrWebTestResultPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.expedia.aggregator.data.WebTestResultCommentType }
     * {@link com.expedia.aggregator.data.WebTestResultTransactionType }
     * {@link com.expedia.aggregator.data.WebTestResultPageType }
     * 
     * 
     */
    public List<Object> getWebTestResultCommentOrWebTestResultTransactionOrWebTestResultPage() {
        if (webTestResultCommentOrWebTestResultTransactionOrWebTestResultPage == null) {
            webTestResultCommentOrWebTestResultTransactionOrWebTestResultPage = new ArrayList<Object>();
        }
        return this.webTestResultCommentOrWebTestResultTransactionOrWebTestResultPage;
    }

}
