//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebTestErrorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WebTestErrorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TestError"/>
 *     &lt;enumeration value="Exception"/>
 *     &lt;enumeration value="HttpError"/>
 *     &lt;enumeration value="ValidationRuleError"/>
 *     &lt;enumeration value="ExtractionRuleError"/>
 *     &lt;enumeration value="Timeout"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WebTestErrorType")
@XmlEnum
public enum WebTestErrorType {

    @XmlEnumValue("TestError")
    TEST_ERROR("TestError"),
    @XmlEnumValue("Exception")
    EXCEPTION("Exception"),
    @XmlEnumValue("HttpError")
    HTTP_ERROR("HttpError"),
    @XmlEnumValue("ValidationRuleError")
    VALIDATION_RULE_ERROR("ValidationRuleError"),
    @XmlEnumValue("ExtractionRuleError")
    EXTRACTION_RULE_ERROR("ExtractionRuleError"),
    @XmlEnumValue("Timeout")
    TIMEOUT("Timeout");
    private final String value;

    WebTestErrorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WebTestErrorType fromValue(String v) {
        for (WebTestErrorType c: WebTestErrorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
