//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.26 at 08:47:47 PM IST 
//


package com.expedia.aggregator.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebTestResultRedirectedPageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WebTestResultRedirectedPageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WebRequestResult" type="{http://microsoft.com/schemas/VisualStudio/TeamTest/2010}WebRequestResultType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WebTestResultRedirectedPageType", propOrder = {
    "webRequestResult"
})
public class WebTestResultRedirectedPageType {

    @XmlElement(name = "WebRequestResult", required = true)
    protected WebRequestResultType webRequestResult;

    /**
     * Gets the value of the webRequestResult property.
     * 
     * @return
     *     possible object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType }
     *     
     */
    public WebRequestResultType getWebRequestResult() {
        return webRequestResult;
    }

    /**
     * Sets the value of the webRequestResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.expedia.aggregator.data.WebRequestResultType }
     *     
     */
    public void setWebRequestResult(WebRequestResultType value) {
        this.webRequestResult = value;
    }

}
