server:

  # The port on which the HTTP server listens for service requests.
  applicationConnectors:

   - type: http

     port: 8080
  # The port on which the HTTP server listens for administrative requests.
  adminConnectors:
    - type: http
      port: 8081

  # The minimum number of threads to keep running to process
  # incoming HTTP requests. Min value can be 8
  minThreads: 24

  # The maximum number of threads to keep running to process
  # incoming HTTP requests. Max value can be 1024
  maxThreads: 256
  

# Logging-specific configuration
#loggingExtended:

  # True if use custom logback configuration else use Dropwizard's default logging
  #resetToLogbackConfigurationXml: true
  
  # recommend to set your own logbackXml file, else atc service uses default 
  # file present in its fat jar   
  #logbackXmlFile: ../configs/logback.xml


# MonitoringSink-specific Configuration
#monitoringSinks:

  # ServeoStats-sink settings  
  #servoStatsdSink:
    #enableServoStatsdSink: true
    #statsdServerHost: 10.0.16.59
    #statsdServerPort: 8125

#Feature Enabled Configuration
#featureCategory:
   #interlineEnabled: true
   #blackListingEnabled: true
   #splitticketingEnabled: false




